# Session 03: Practice

## Datetimes and Timeseries with Pandas

We will use the Spanish power market dataset to practice working with datetimes and timeseries in Pandas. The dataset contains hourly electricity prices and demand data for Spain.

In this practical session, we will apply the following datetime concepts:

1. Pandas for Time Series and Business Data
   - Timestamps, Periods, Timedeltas
   - Creating and converting date columns

2. Indexing and Slicing Time Series Data
   - Date-based filtering and selection
   - Time-based data access

3. Generating Date Ranges for Business Use
   - Creating date sequences

4. Practical Frequency Codes for Business
   - Hourly, daily, weekly, monthly frequencies

5. Advanced Operations
   - Resampling and frequency conversion
   - Time shifting and lag calculations
   - Rolling windows and moving averages

Let's start by exploring our Spanish power market dataset!

In [1]:
import pandas as pd

energy = pd.read_csv("power_market_spain_2025.csv")

energy.head()

,datetime,spot_price,gen_ccgt,gen_coal,gen_hydro,gen_nuclear,gen_solar_pv,gen_solar_th,gen_total,gen_wind,demand_total
0,2025-01-01 00:00:00+00:00,134.49,2888.0,243.6,3436.6,7089.9,61.6,350.0,20742.6,3877.6,20825.2
1,2025-01-01 01:00:00+00:00,131.59,1853.5,243.2,3243.3,7087.9,59.6,378.3,19705.7,4049.7,19783.0
2,2025-01-01 02:00:00+00:00,131.49,710.0,180.0,2958.8,7088.9,67.8,378.3,18387.9,4211.4,18502.5
3,2025-01-01 03:00:00+00:00,131.42,NaN,NaN,2667.0,7088.9,67.8,378.3,17309.5,4311.8,17497.5
4,2025-01-01 04:00:00+00:00,120.49,NaN,NaN,2104.4,7088.9,57.6,378.4,16573.1,4383.0,16798.5

## 1. Pandas for Time Series and Business Data
   - Creating and converting date columns
   - Timestamps, Periods, Timedeltas

In [2]:
energy.dtypes

datetime         object
spot_price      float64
gen_ccgt        float64
gen_coal        float64
gen_hydro       float64
gen_nuclear     float64
gen_solar_pv    float64
gen_solar_th    float64
gen_total       float64
gen_wind        float64
demand_total    float64
dtype: object

In [3]:
# convert the 'datetime' column to datetime format

energy["datetime"] = pd.to_datetime(energy["datetime"])

energy["datetime"].dtype

datetime64[ns, UTC]

In [4]:
# create new columns for year, month, isoweek, day, hour, and date

energy["year"] = energy["datetime"].dt.year
energy["month"] = energy["datetime"].dt.month
energy["isoweek"] = energy["datetime"].dt.isocalendar().week
energy["day"] = energy["datetime"].dt.day
energy["hour"] = energy["datetime"].dt.hour
energy["date"] = energy["datetime"].dt.date

energy.head()

,datetime,spot_price,gen_ccgt,gen_coal,gen_hydro,gen_nuclear,gen_solar_pv,gen_solar_th,gen_total,gen_wind,demand_total,year,month,isoweek,day,hour,date
0,2025-01-01 00:00:00+00:00,134.49,2888.0,243.6,3436.6,7089.9,61.6,350.0,20742.6,3877.6,20825.2,2025,1,1,1,0,2025-01-01
1,2025-01-01 01:00:00+00:00,131.59,1853.5,243.2,3243.3,7087.9,59.6,378.3,19705.7,4049.7,19783.0,2025,1,1,1,1,2025-01-01
2,2025-01-01 02:00:00+00:00,131.49,710.0,180.0,2958.8,7088.9,67.8,378.3,18387.9,4211.4,18502.5,2025,1,1,1,2,2025-01-01
3,2025-01-01 03:00:00+00:00,131.42,NaN,NaN,2667.0,7088.9,67.8,378.3,17309.5,4311.8,17497.5,2025,1,1,1,3,2025-01-01
4,2025-01-01 04:00:00+00:00,120.49,NaN,NaN,2104.4,7088.9,57.6,378.4,16573.1,4383.0,16798.5,2025,1,1,1,4,2025-01-01

In [5]:
# create new columns for day of the week and day and is_weekend

energy["day_of_week"] = energy["datetime"].dt.dayofweek
energy["is_weekend"] = energy["day_of_week"].isin([5, 6])  # 5 = Saturday, 6 = Sunday

energy.head()

,datetime,spot_price,gen_ccgt,gen_coal,gen_hydro,gen_nuclear,gen_solar_pv,gen_solar_th,gen_total,gen_wind,demand_total,year,month,isoweek,day,hour,date,day_of_week,is_weekend
0,2025-01-01 00:00:00+00:00,134.49,2888.0,243.6,3436.6,7089.9,61.6,350.0,20742.6,3877.6,20825.2,2025,1,1,1,0,2025-01-01,2,False
1,2025-01-01 01:00:00+00:00,131.59,1853.5,243.2,3243.3,7087.9,59.6,378.3,19705.7,4049.7,19783.0,2025,1,1,1,1,2025-01-01,2,False
2,2025-01-01 02:00:00+00:00,131.49,710.0,180.0,2958.8,7088.9,67.8,378.3,18387.9,4211.4,18502.5,2025,1,1,1,2,2025-01-01,2,False
3,2025-01-01 03:00:00+00:00,131.42,NaN,NaN,2667.0,7088.9,67.8,378.3,17309.5,4311.8,17497.5,2025,1,1,1,3,2025-01-01,2,False
4,2025-01-01 04:00:00+00:00,120.49,NaN,NaN,2104.4,7088.9,57.6,378.4,16573.1,4383.0,16798.5,2025,1,1,1,4,2025-01-01,2,False

In [6]:
# create column for quarters

energy["quarter"] = energy["datetime"].dt.quarter

In [7]:
energy["quarter"].unique()

array([1, 2], dtype=int32)

In [8]:
energy["month"].unique()

array([1, 3, 4, 5, 2, 6], dtype=int32)

## 2. Indexing and Slicing Time Series Data
   - Date-based filtering and selection
   - Time-based data access

In [ ]:
# set 'datetime' as index minus the timezone information

energy["datetime"] = energy["datetime"].dt.tz_localize(None)

energy.set_index("datetime", inplace=True)

energy.head()

,spot_price,gen_ccgt,gen_coal,gen_hydro,gen_nuclear,gen_solar_pv,gen_solar_th,gen_total,gen_wind,demand_total,year,month,isoweek,day,hour,date,day_of_week,is_weekend,quarter
datetime,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00,134.49,2888.0,243.6,3436.6,7089.9,61.6,350.0,20742.6,3877.6,20825.2,2025,1,1,1,0,2025-01-01,2,False,1
2025-01-01 01:00:00,131.59,1853.5,243.2,3243.3,7087.9,59.6,378.3,19705.7,4049.7,19783.0,2025,1,1,1,1,2025-01-01,2,False,1
2025-01-01 02:00:00,131.49,710.0,180.0,2958.8,7088.9,67.8,378.3,18387.9,4211.4,18502.5,2025,1,1,1,2,2025-01-01,2,False,1
2025-01-01 03:00:00,131.42,NaN,NaN,2667.0,7088.9,67.8,378.3,17309.5,4311.8,17497.5,2025,1,1,1,3,2025-01-01,2,False,1
2025-01-01 04:00:00,120.49,NaN,NaN,2104.4,7088.9,57.6,378.4,16573.1,4383.0,16798.5,2025,1,1,1,4,2025-01-01,2,False,1

In [10]:
# extract data from april 2025

energy_april_2025 = energy[(energy["year"] == 2025) & (energy["month"] == 4)]

energy_april_2025

,spot_price,gen_ccgt,gen_coal,gen_hydro,gen_nuclear,gen_solar_pv,gen_solar_th,gen_total,gen_wind,demand_total,year,month,isoweek,day,hour,date,day_of_week,is_weekend,quarter
datetime,,,,,,,,,,,,,,,,,,,
2025-04-30 23:00:00,29.20,NaN,NaN,7122.5,NaN,12.2,343.8,22845.3,11320.1,21185.9,2025,4,18,30,23,2025-04-30,2,False,2
2025-04-01 00:00:00,75.78,NaN,NaN,7407.9,6106.5,12.2,589.4,20294.1,2793.2,22779.4,2025,4,14,1,0,2025-04-01,1,False,2
2025-04-01 01:00:00,70.03,NaN,NaN,6769.1,6106.5,12.2,589.6,19701.9,2833.2,21710.7,2025,4,14,1,1,2025-04-01,1,False,2
2025-04-01 02:00:00,60.48,NaN,NaN,6758.6,6107.5,12.2,589.6,19657.8,2797.4,21378.6,2025,4,14,1,2,2025-04-01,1,False,2
2025-04-01 03:00:00,61.59,NaN,NaN,6832.8,6107.5,12.2,574.6,19685.2,2755.5,21376.1,2025,4,14,1,3,2025-04-01,1,False,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-29 19:00:00,12.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,4,18,29,19,2025-04-29,1,False,2
2025-04-29 20:00:00,35.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,4,18,29,20,2025-04-29,1,False,2
2025-04-29 21:00:00,33.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,4,18,29,21,2025-04-29,1,False,2
2025-04-29 22:00:00,17.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,4,18,29,22,2025-04-29,1,False,2
2025-04-29 23:00:00,35.00,NaN,NaN,6449.8,90.1,6.2,245.9,23070.8,12186.8,22957.8,2025,4,18,29,23,2025-04-29,1,False,2

## 3. Generating Date Ranges for Business Use
   - Creating date sequences
   - Business day calculations

Sometimes it's easier to create a date_range and then filter the data based on that range. Let's create a date range for April 2025 and filter our dataset accordingly.

In [11]:
# create a date range for some days in January 2025
date_range = pd.date_range(start="2025-01-01", end="2025-01-12", freq="h")

# filter the energy data for the date range
january_2025_data = energy.loc[date_range]

january_2025_data

,spot_price,gen_ccgt,gen_coal,gen_hydro,gen_nuclear,gen_solar_pv,gen_solar_th,gen_total,gen_wind,demand_total,year,month,isoweek,day,hour,date,day_of_week,is_weekend,quarter
2025-01-01 00:00:00,134.49,2888.0,243.6,3436.6,7089.9,61.6,350.0,20742.6,3877.6,20825.2,2025,1,1,1,0,2025-01-01,2,False,1
2025-01-01 01:00:00,131.59,1853.5,243.2,3243.3,7087.9,59.6,378.3,19705.7,4049.7,19783.0,2025,1,1,1,1,2025-01-01,2,False,1
2025-01-01 02:00:00,131.49,710.0,180.0,2958.8,7088.9,67.8,378.3,18387.9,4211.4,18502.5,2025,1,1,1,2,2025-01-01,2,False,1
2025-01-01 03:00:00,131.42,NaN,NaN,2667.0,7088.9,67.8,378.3,17309.5,4311.8,17497.5,2025,1,1,1,3,2025-01-01,2,False,1
2025-01-01 04:00:00,120.49,NaN,NaN,2104.4,7088.9,57.6,378.4,16573.1,4383.0,16798.5,2025,1,1,1,4,2025-01-01,2,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-11 20:00:00,119.95,NaN,NaN,6433.1,7074.7,48.3,306.4,32579.5,13921.0,29421.6,2025,1,2,11,20,2025-01-11,5,True,1
2025-01-11 21:00:00,116.20,NaN,NaN,5391.0,7075.7,48.3,296.4,30603.3,13836.0,29259.9,2025,1,2,11,21,2025-01-11,5,True,1
2025-01-11 22:00:00,113.27,NaN,NaN,4713.5,7075.7,48.3,296.3,29886.3,13817.8,27407.3,2025,1,2,11,22,2025-01-11,5,True,1
2025-01-11 23:00:00,106.10,NaN,NaN,4168.9,7076.7,55.6,296.3,28723.0,13681.8,25303.4,2025,1,2,11,23,2025-01-11,5,True,1
2025-01-12 00:00:00,110.36,NaN,243.6,3402.8,7078.1,66.9,314.4,28316.5,13839.2,23870.7,2025,1,2,12,0,2025-01-12,6,True,1

## 5. Advanced Operations
   - Resampling and frequency conversion
   - Time shifting and lag calculations
   - Rolling windows and moving averages

In [12]:
# plot demand in isoweek 21 hourly vs daily (resampled) vs daily (as_freq)

isoweek_21 = energy[(energy["isoweek"] == 21)]

hourly_demand_isoweek_21 = isoweek_21["demand_total"]

# plot hourly demand plotly

import plotly.express as px

fig = px.line(
    hourly_demand_isoweek_21,
    x=hourly_demand_isoweek_21.index,
    y="demand_total",
    title="Hourly Demand in Isoweek 21",
)
fig.update_xaxes(title_text="Datetime")
fig.update_yaxes(title_text="Demand (MW)")
fig.show()

In [13]:
# now resample to daily frequency

daily_demand_isoweek_21 = isoweek_21["demand_total"].resample("D").mean()

# add it to the plot

fig.add_scatter(
    x=daily_demand_isoweek_21.index,
    y=daily_demand_isoweek_21,
    mode="lines",
    name="Daily Resampled Demand",
)

fig.update_layout(title="Hourly vs Daily Resampled Demand in Isoweek 21")
fig.show()

In [14]:
# now use as_freq to get daily data

daily_demand_isoweek_21_as_freq = isoweek_21["demand_total"].asfreq("D")

# add it to the plot

fig.add_scatter(
    x=daily_demand_isoweek_21_as_freq.index,
    y=daily_demand_isoweek_21_as_freq,
    mode="lines",
    name="Daily As Frequency Demand",
)

fig.update_layout(title="Hourly vs Daily As Frequency Demand in Isoweek 21")
fig.show()

Both options are valid to extract one aggregated value per day, but they have different implications:

* `resample('D')` will aggregate the data by taking the mean of all values within each day, which is useful for continuous data like demand or prices.
* `asfreq('D')` will return the first value of each day, which is useful for discrete data or when you want to maintain the original values without aggregation.

In [15]:
# compare the hourly spot price with the price in the previous hour using the shift method

energy["spot_price_previous_hour"] = energy["spot_price"].shift(1)

energy[["spot_price", "spot_price_previous_hour"]].head()

                     spot_price  spot_price_previous_hour
datetime
2025-01-01 00:00:00      134.49                       NaN
2025-01-01 01:00:00      131.59                    134.49
2025-01-01 02:00:00      131.49                    131.59
2025-01-01 03:00:00      131.42                    131.49
2025-01-01 04:00:00      120.49                    131.42

In [16]:
# plot the two series (price and previous hour price) with plotly
# with a scatter plot in plotly with red trendline

fig = px.scatter(
    energy[["spot_price", "spot_price_previous_hour"]].dropna(),
    x="spot_price_previous_hour",
    y="spot_price",
)

# add opacity 0.3
fig.update_traces(marker=dict(opacity=0.3))

# update layout with title and axis labels
fig.update_layout(title="Spot Price vs Previous Hour Spot Price")
fig.update_xaxes(title_text="Previous Hour Spot Price (EUR/MWh)")
fig.update_yaxes(title_text="Spot Price (EUR/MWh)")
fig.show()

In [17]:
# seems to be quite correlated, let's calculate the correlation coefficient

correlation = energy["spot_price"].corr(energy["spot_price_previous_hour"])

print(f"Correlation between spot price and previous hour spot price: {correlation:.2f}")

Correlation between spot price and previous hour spot price: 0.95

In [18]:
# use rolling windows of demand to evaluate its trend over time

energy["rm24_demand"] = energy["demand_total"].rolling(window=24).mean()

# filter for isoweek 21 to plot the rolling mean
isoweek_21 = energy[(energy["isoweek"] == 21)]

# plot the demand and rolling mean with plotly in isoweek 21

fig = px.line(
    isoweek_21[["demand_total", "rm24_demand"]],
    x=isoweek_21.index,
    y=["demand_total", "rm24_demand"],
    labels={"value": "Demand (MW)", "variable": "Series"},
    title="Demand and 24-Hour Rolling Mean in Isoweek 21",
)
fig.update_xaxes(title_text="Datetime")
fig.update_yaxes(title_text="Demand (MW)")
fig.show()

In [19]:
# now rolling window of 1 week to see the trend over a month of hourly data

energy["rm168_demand"] = energy["demand_total"].rolling(window=168).mean()


june_2025 = energy[(energy["year"] == 2025) & (energy["month"] == 6)]

# plot the demand and rolling mean with plotly in June 2025
fig = px.line(
    june_2025[["demand_total", "rm168_demand"]],
    x=june_2025.index,
    y=["demand_total", "rm168_demand"],
    labels={"value": "Demand (MW)", "variable": "Series"},
    title="Demand and 168-Hour Rolling Mean in June 2025",
)

fig.update_xaxes(title_text="Datetime")
fig.update_yaxes(title_text="Demand (MW)")
fig.show()

As we can see, rolling windows allow us to calculate moving averages, which can help smooth out fluctuations in the data and highlight longer-term trends.