# Session 11: Introduction to Pandas and data manipulation

`pandas` is a Python library that uses `NumPy` under the hood. `pandas` allows us to perform data analysis and manipulation for tabular data. 

We can use pandas by importing it
```Python
import pandas
```
Or using its well known alias `pd`
```Python
import pandas as pd
```

In [70]:
!pip install pandas

Requirement already satisfied: pandas in /Users/dgh/miniconda3/envs/pda/lib/python3.10/site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /Users/dgh/miniconda3/envs/pda/lib/python3.10/site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dgh/miniconda3/envs/pda/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/dgh/miniconda3/envs/pda/lib/python3.10/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/dgh/miniconda3/envs/pda/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/dgh/miniconda3/envs/pda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [71]:
# importing pandas as its shorter alias: pd
import pandas as pd

Now that we have loaded `pandas` we can start using it. But first, some of its main classes and functionalities.

## Pandas series

`pd.Series` is a pandas object that contains one dimensional data in an array-like data structure.

For each element in a `pd.Series`, a label is assigned to it: the `index`.

`pd.Series` can be created from lists, dictionaries, `NumPy` arrays, etc, and can contain integers, floats, strings, booleans, datetimes, ...

Let's create a series that contains the following elements `[1, 2, 3]` and let's assign the following labels (`index`) to them `["elem1", "elem2", "elem3"]`

In [76]:
type(2)

int

In [78]:
# specifying the index

# numpy
my_series = pd.Series(
    [1, 2, 3]
)

my_series

0    1
1    2
2    3
dtype: int64

In [79]:
my_series

0    1
1    2
2    3
dtype: int64

In [80]:
s = pd.Series(['a', 1, 2.3])

s

0      a
1      1
2    2.3
dtype: object

In [88]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [89]:
s

0      a
1      1
2    2.3
dtype: object

In [90]:
s.values

array(['a', 1, 2.3], dtype=object)

In [7]:
pd.Series({"a": 1, "b": 2})

a    1
b    2
dtype: int64

In [91]:
# without specifying the index you get an index of 0, 1, 2

s = pd.Series(
    [1, 2, 3, 4],
    index=["elem1", "elem2", "elem3", "elem4"]
)

s

elem1    1
elem2    2
elem3    3
elem4    4
dtype: int64

In [92]:
pd.Series(
    dict(zip(["elem1", "elem2", "elem3", "elem4"], [1, 2, 3, 4]))
)

elem1    1
elem2    2
elem3    3
elem4    4
dtype: int64

In [9]:
s.index

Index(['elem1', 'elem2', 'elem3', 'elem4'], dtype='object')

### Series elements

`pd.Series` have two main properties: `values` and `index`. 

We can extract the values contained in a series or the index that labels the values.

In [10]:
print(s.values)
print(type(s.values))

[1 2 3 4]
<class 'numpy.ndarray'>

In [94]:

print(s.dtype)
s

int64

elem1    1
elem2    2
elem3    3
elem4    4
dtype: int64

In [12]:
list(s.values)

[1, 2, 3, 4]

In [13]:
print(s.index)
print(type(s.index))

Index(['elem1', 'elem2', 'elem3', 'elem4'], dtype='object')
<class 'pandas.core.indexes.base.Index'>

As we can see, the `values` are a `NumPy` array, whereas the `index` is a `pandas.Index` object

When `index` is not specified, `pandas` will use 0, 1, ..., N as indices.

In [14]:
s[0]

/var/folders/m6/c304cbwn6016v9v4lv618s740000gn/T/ipykernel_33282/243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]

1

In [15]:
my_series = pd.Series(
    [1, 2, 3],
    index=range(3,6)
)

my_series

3    1
4    2
5    3
dtype: int64

### Creating `pd.Series`

We can use the following objects as the argument of `pd.Series`

* From `list`, `tuple`
* From `np.array`
* From `dict`
* From `range()`

In [16]:
pd.Series([
    {"a":1}, {"a":1}, {"a":1}
])

0    {'a': 1}
1    {'a': 1}
2    {'a': 1}
dtype: object

In [95]:
import numpy as np

# from list
s_list = pd.Series(["1", "2", "3"])

# from tuple
s_tuple = pd.Series(("1", "2", "3"))

# from np.array
s_array = pd.Series(np.array((1, 2, 3)))

# from dict
s_dict = pd.Series({"x": 1, "y": 2, "z": 3, })

# from range
s_range = pd.Series(range(5))

print(f"Series from list: {s_list}")
print(f"Series from tuple: {s_tuple}")
print(f"Series from array: {s_array}")
print(f"Series from dict: {s_dict}")
print(f"Series from range: {s_range}")

Series from list: 0    1
1    2
2    3
dtype: object
Series from tuple: 0    1
1    2
2    3
dtype: object
Series from array: 0    1
1    2
2    3
dtype: int64
Series from dict: x    1
y    2
z    3
dtype: int64
Series from range: 0    0
1    1
2    2
3    3
4    4
dtype: int64

### `pd.Series` basic properties and methods

In [18]:
s = pd.Series([1, 2, 3, 4])

In [96]:
s

elem1    1
elem2    2
elem3    3
elem4    4
dtype: int64

In [97]:
# length: `len(s)`

len(s)

4

In [21]:
# shape: `s.shape`
s.shape

(4,)

In [22]:
len(s)==s.shape[0]

True

In [23]:
# type of elements

s = pd.Series([1, 2, 3])

s.dtype

dtype('int64')

In [24]:
a = pd.Series(["a", 2.0, 1])

a

0      a
1    2.0
2      1
dtype: object

In [25]:
type(a[1])

float

In [99]:
my_dict = {
    "a": 1,
    "b": 2
}

my_dict.get("c")

In [27]:
my_dict = {"b": 1, "a": 2}

my_dict.get("g")

In [101]:
# selecting a certain element according to the index: `get()`
ser = pd.Series({"a": 1, "b": 2, "c": 3})

ser.get("b")

2

## Pandas DataFrames

If we aggregate several series together we can build a `pd.DataFrame`. These objects are table-like structures in which each row is represented by its own `index` and each column is represented by a column name.

A `pd.DataFrame` is, in the end, a `NumPy` matrix of `n` rows and `m` columns, with labels for each row and column.

### How to create a `pd.DataFrame`

We can use the following objects as the argument of `pd.DataFrame`

* From dict of `pd.Series`: the keys will be the name of the columns
* From list of dicts: the keys will be the name of the columns
* From dict of lists: the keys will be the name of the columns 
...

In [29]:
# from dict of pd.Series

series1 = pd.Series([1, 2, 3, 4])
series2 = pd.Series([2, 3, 4, 5])

df = pd.DataFrame(
    {
        "var1": series1,
        "var2": series2
    }
)

df

   var1  var2
0     1     2
1     2     3
2     3     4
3     4     5

In [102]:
df = pd.DataFrame(
    {
        "dani": [1, 2, 3],
        "pedro": ["a", "b", "c"]
    }
)

df

   dani pedro
0     1     a
1     2     b
2     3     c

In [103]:
df.values

array([[1, 'a'],
       [2, 'b'],
       [3, 'c']], dtype=object)

In [32]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [33]:
df.columns

Index(['dani', 'pedro'], dtype='object')

In [104]:
# from list of dicts

list_of_dicts = [
    {"Name": "Daniel", "Age": None, "Furry": False, "Height": 178},
    {"Name": "Churro", "Age": None, "Furry": True, "Height": 60},
    {"Age": None, "Furry": False, "Height": 40},
]

pd.DataFrame(list_of_dicts)

     Name   Age  Furry  Height
0  Daniel  None  False     178
1  Churro  None   True      60
2     NaN  None  False      40

In [35]:
# from dict of lists
dict_lists = {
    "var1": ["Good", "Average", "Bad"],
    "var2": [32, 6, 1],
    "var3": [False, True, None],
    "var4": [178, 60, 40]
}

pd.DataFrame(dict_lists)

      var1  var2   var3  var4
0     Good    32  False   178
1  Average     6   True    60
2      Bad     1   None    40

### `pd.DataFrame` basic properties and methods

In [53]:
df = pd.DataFrame({
    "col_float": [1.0, 2.3, 5.66],
    "col_int": [1, 2, 3],
    "col_string": ["abc", "abc", "ghi"],
    "col_boolean": [True, True, False]
})

df

   col_float  col_int col_string  col_boolean
0       1.00        1        abc         True
1       2.30        2        abc         True
2       5.66        3        ghi        False

#### Values:

`df.values` is the actual information contained and labelled in our dataframe.

Returns an `np.array`. These are formed as a list of list in which each sublist contains the rows of the matrix

In [105]:
# values: np.array
# np.arrays are formed as a list of list in which each sublist contains the rows of the matrix

df.values

array([[1, 'a'],
       [2, 'b'],
       [3, 'c']], dtype=object)

#### Index:

We can see the index used in our DF by using the `index` property. We will receive a generator that we can unfold with `list()` for example

We can also change this index to any other info we want with `df.set_index()`.

If we pass the argument `drop=False` we will not remove the column from the values, and we'll have it as index AND in the values. Otherwise, it will be removed.

In [125]:
df = pd.DataFrame({
    "col_float": [1.0, 2.3, 5.66],
    "col_int": [1, 2, 3],
    "col_string": ["abc", "abc", "ghi"],
    "col_boolean": [True, True, False]
}, index=['a', 'b', 'c'])

df

   col_float  col_int col_string  col_boolean
a       1.00        1        abc         True
b       2.30        2        abc         True
c       5.66        3        ghi        False

In [115]:
df

   col_float  col_int col_string  col_boolean
a       1.00        1        abc         True
b       2.30        2        abc         True
c       5.66        3        ghi        False

Just like some other operations, set_index is not done in place, so we need to assign the result to a new variable or to the same one.

In [117]:
df = df.set_index("col_float") # this will save the column as the index

           col_int col_string  col_boolean
col_float
1.00             1        abc         True
2.30             2        abc         True
5.66             3        ghi        False

In [127]:
df.set_index("col_float", inplace=True)

In [120]:
df

           col_int col_string  col_boolean
col_float
1.00             1        abc         True
2.30             2        abc         True
5.66             3        ghi        False

In [121]:
df.shape

(3, 3)

In [57]:
# this will not save the column as the index
# it will just return a new DataFrame with the column as the index

df.set_index('col_int')

        col_string  col_boolean
col_int
1              abc         True
2              abc         True
3              ghi        False

We can revert the index to the default one with `df.reset_index()`. This will remove the current index and replace it with the default one (0, 1, ..., N).

If we want to remove the current index and not add it as a column, we can use `df.reset_index(drop=True)`.

In [ ]:
df.reset_index()

In [124]:
df

   col_float  col_int col_string  col_boolean
0       1.00        1        abc         True
1       2.30        2        abc         True
2       5.66        3        ghi        False

In general, in pandas, we can use the `inplace=True/False` argument to modify the object in place or return a new one.

This is handy when we want to keep the overwrite the original object or not.

In [60]:
df

           col_int col_string  col_boolean
col_float
1.00             1        abc         True
2.30             2        abc         True
5.66             3        ghi        False

In [ ]:
# this will save the result without returning a new DataFrame

df.set_index("col_int", inplace=True)

# without having to do df = df.set_index("col_int")

#### Columns and their names:

`df.columns` return the labels attached to each column, or their names.

We can mutate this by mutating the `df.columns` values, or by using `df.rename()` passing as argument a dict with keys containing the old columns we want to change, and value the new name.

In [133]:
df = pd.DataFrame({
    "col_float": [1.0, 2.3, 5.66],
    "col_int": [1, 2, 3],
    "col_string": ["abc", "abc", "ghi"],
    "col_boolean": [True, True, False]
})

df

   col_float  col_int col_string  col_boolean
0       1.00        1        abc         True
1       2.30        2        abc         True
2       5.66        3        ghi        False

In [130]:
# get the columns names
df.columns

Index(['col_float', 'col_int', 'col_string', 'col_boolean'], dtype='object')

In [63]:
df

   col_float  col_int col_string  col_boolean
0       1.00        1        abc         True
1       2.30        2        abc         True
2       5.66        3        ghi        False

In [134]:
df.columns = [colname.replace("col", "type") for colname in df.columns]

df

   type_float  type_int type_string  type_boolean
0        1.00         1         abc          True
1        2.30         2         abc          True
2        5.66         3         ghi         False

We can also rename columns by using the `.rename()` method, passing a dictionary with the old column names as keys and the new names as values.

In [135]:
df.rename(
    columns={
        "type_float": "col01",
        "type_int": "col02"
    },
    inplace=True # this will save the changes in the original DataFrame
)

df

   col01  col02 type_string  type_boolean
0   1.00      1         abc          True
1   2.30      2         abc          True
2   5.66      3         ghi         False

In [ ]:
df

   asdfqasdf  col02 col03  col04
0       1.00      1   abc   True
1       2.30      2   abc   True
2       5.66      3   ghi  False

#### Describe 

`df.describe()` returns a summary with statistics for the numeric columns, very useful for Exploratory Data Analysis

In [141]:
df = pd.DataFrame({
    "col_float": [1.0, 2.3, 5.66],
    "col_int": [1, 2, 3],
    "col_string": ["abc", "abc", "ghi"],
    "col_boolean": [True, True, False]
})

summary = df.describe()

In [144]:
df.dtypes

col_float      float64
col_int          int64
col_string      object
col_boolean       bool
dtype: object

#### Transpose

Since DataFrames are matrices, we can transpose them with `df.T`

Basically this converts rows into columns and columns into rows.

In [145]:
df

   col_float  col_int col_string  col_boolean
0       1.00        1        abc         True
1       2.30        2        abc         True
2       5.66        3        ghi        False

In [152]:
df.T

                0     1      2
col_float     1.0   2.3   5.66
col_int         1     2      3
col_string    abc   abc    ghi
col_boolean  True  True  False

In [146]:
df.T.T

  col_float col_int col_string col_boolean
0       1.0       1        abc        True
1       2.3       2        abc        True
2      5.66       3        ghi       False

## Indexing and slicing

We can create subsets of our `pandas` objects in different ways:

* `df.loc[label_row_start:label_row_end, label_col_start:label_col_end]` to slice by label
* `df.iloc[pos_row_start:pos_row_end, pos_col_start:pos_col_end]` to slice by position
* Good old []

In [ ]:
a = [1, 2, 3, 4]

a[1:3]

[2, 3]

In [153]:
df = pd.DataFrame({
    "col_float": [1.0, 2.3, 5.66, 9.99],
    "col_int": [1, 2, 3, 4],
    "col_string": ["abc", "abc", "ghi", "jkl"],
    "col_boolean": [True, True, False, True]
})

# set `col_string` as index
df = df.set_index("col_string")

df

            col_float  col_int  col_boolean
col_string
abc              1.00        1         True
abc              2.30        2         True
ghi              5.66        3        False
jkl              9.99        4         True

Now we have string labels for rows (`"abc", "def", "ghi"`) and columns (`"col_float", "col_int", "col_boolean"`)

### Slicing based on single values as arguments

* `loc[row_label, column_label]`
* `iloc[row_position, column_position]`

In [154]:
df

            col_float  col_int  col_boolean
col_string
abc              1.00        1         True
abc              2.30        2         True
ghi              5.66        3        False
jkl              9.99        4         True

In [155]:
# value at second row and second column: using loc
df.loc['abc', "col_int"] # all the rows but just the column called `col_int`

col_string
abc    1
abc    2
Name: col_int, dtype: int64

In [158]:
df.loc["abc", :]

            col_float  col_int  col_boolean
col_string
abc               1.0        1         True
abc               2.3        2         True

In [161]:
df

            col_float  col_int  col_boolean
col_string
abc              1.00        1         True
abc              2.30        2         True
ghi              5.66        3        False
jkl              9.99        4         True

In [162]:
# value at second row and second column: using iloc
df.iloc[1, 1]

2

We can also get all the row or all the column by using `:`

In [164]:
df

            col_float  col_int  col_boolean
col_string
abc              1.00        1         True
abc              2.30        2         True
ghi              5.66        3        False
jkl              9.99        4         True

In [163]:
# getting the 3rd row using loc
df.loc["ghi", :]

col_float       5.66
col_int            3
col_boolean    False
Name: ghi, dtype: object

In [165]:
# getting the 3rd row using iloc
df.iloc[2, :]

col_float       5.66
col_int            3
col_boolean    False
Name: ghi, dtype: object

In [ ]:
# to get the whole column we can use `:` in the rows position

# with loc
df.loc[:, "col_float"]

col_string
abc    1.00
abc    2.30
ghi    5.66
jkl    9.99
Name: col_float, dtype: float64

In [ ]:
# with iloc
df.iloc[:, 0]

col_string
abc    1.00
abc    2.30
ghi    5.66
jkl    9.99
Name: col_float, dtype: float64

In [ ]:
""" df = pd.DataFrame({'a': [1, 2, 3]}, index=[100, 22, 45])

df """

NameError: name 'pd' is not defined

In [ ]:
df.iloc[1, :]

a    2
Name: 22, dtype: int64

We can do all this for columns with just square brackets `[]` and the name of the column:

In [167]:
df.loc[:, 'col_int']

col_string
abc    1
abc    2
ghi    3
jkl    4
Name: col_int, dtype: int64

In [170]:
df[['col_float', 'col_boolean']]

            col_float  col_boolean
col_string
abc              1.00         True
abc              2.30         True
ghi              5.66        False
jkl              9.99         True

In [171]:
df.col_float

col_string
abc    1.00
abc    2.30
ghi    5.66
jkl    9.99
Name: col_float, dtype: float64

In [ ]:
df_copy = df.copy()

In [ ]:
df['b'] = [10, 20, 30]

df_copy = df.copy()

df_copy

     a   b
100  1  10
22   2  20
45   3  30

In [ ]:
df_copy.loc[:, 'a'] = df_copy.loc[:, 'a']**2

df_copy

     a   b
100  1  10
22   4  20
45   9  30

In [ ]:
# change the values of the third row by 3 times the third row

df_copy.iloc[2, :] = df_copy.iloc[2, :] * 3

df_copy

      a   b
100   1  10
22    4  20
45   27  90

In [ ]:
# c contains the square of a
df_copy['c'] = df_copy['a'].map(lambda x: x ** 2)

df_copy

      a   b    c
100   1  10    1
22    4  20   16
45   27  90  729

In [ ]:
df["col_int"] # extracting a single column as a series

col_string
abc    1
def    2
ghi    3
jkl    4
Name: col_int, dtype: int64

In [ ]:
df[["col_int"]] # extracting a single column as a dataframe

            col_int
col_string
abc               1
def               2
ghi               3
jkl               4

In [ ]:
df[["col_float", "col_int"]]

            col_float  col_int
col_string
abc              1.00        1
def              2.30        2
ghi              5.66        3
jkl              9.99        4

### Slicing based on several values: lists or ranges.

* Using ranges of values:
  * Using `loc`: when using `loc` the final value **WILL BE INCLUDED**
    * df.loc[ini_row_label:end_row_label, ini_col_label:end_col_label]
  * Using `iloc`
    * df.iloc[ini_row_position:end_row_position, ini_col_position:end_col_position]
    
* Using list of values:
  * Using `loc`:
    * df.loc[[row_labels_to_include], [col_labels_to_include]]
  * Using `iloc`
    * df.iloc[[row_positions_to_include], [col_positions_to_include]]

In [ ]:
df

            col_float  col_int  col_boolean
col_string
abc              1.00        1         True
def              2.30        2         True
ghi              5.66        3        False
jkl              9.99        4         True

In [ ]:
# get the last 3 rows for the last 2 columns
# using ranges and loc


df.loc[:, 'col_float']

col_string
abc    1.00
abc    2.30
ghi    5.66
Name: col_float, dtype: float64

In [ ]:
df[['col_float']]

            col_float
col_string
abc              1.00
abc              2.30
ghi              5.66

In [ ]:
# get the last 3 rows for the last 2 columns
# using ranges and iloc
df.iloc[-3:, -2:]

            col_int  col_boolean
col_string
abc               1         True
abc               2         True
ghi               3        False

In [ ]:
# get the 2nd and 4th row for the 2nd column
# using lists and loc
df.loc[["def", "jkl"], "col_int"]

col_string
def    2
jkl    4
Name: col_int, dtype: int64

In [ ]:
# get the 2nd and 4th row for the 2nd column
# using lists and iloc
df.iloc[[1, 3], 1]

col_string
def    2
jkl    4
Name: col_int, dtype: int64

### Slicing based on conditions

Before diving into it, let's see what `pandas` return when we perform logical operations on a series

In [172]:
# create series
s = pd.Series([1, 2, 3, 4, 5])

s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [174]:
my_filter = s > 3 # mask

my_filter

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [ ]:
s[my_filter] # applying mask to series

3    4
4    5
dtype: int64

In [ ]:
# create series
s = pd.Series([1, 2, 3, 4, 5])

# condition
s[s>3]

3    4
4    5
dtype: int64

In [ ]:
True & False

False

In [ ]:
condition = (s > 3) and (s % 2 == 0)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
s[condition] # concatenate conditions

3    4
dtype: int64

### equivalences pandas - native python for logical operators

Python - Pandas

* `and` - `&`
* `or` - `|`
* `not` - `~`

The result is another `pd.Series` filled with `True/False` according to whether or not the condition was met for each element.

We can use this to *filter* series, by including the condition between brackets.

```Python
series[series[condition]]
```

### logical operators in pandas
* and: &
* or: |
* not: ~

In [180]:
s = pd.Series(range(1,51,2))

s[(s % 5 == 0) & (s > 12)]

7     15
12    25
17    35
22    45
dtype: int64

In [181]:
s[(s % 5 == 0) | (s % 7 == 0)]

2      5
3      7
7     15
10    21
12    25
17    35
22    45
24    49
dtype: int64

In [184]:
s[~(s%2==0)]

0      1
1      3
2      5
3      7
4      9
5     11
6     13
7     15
8     17
9     19
10    21
11    23
12    25
13    27
14    29
15    31
16    33
17    35
18    37
19    39
20    41
21    43
22    45
23    47
24    49
dtype: int64

We can extend this behaviors to DataFrames: we can filter the rows of our df based on logical conditions on the columns.

In [185]:
# defining the dataset
df = pd.DataFrame({
    "col_a": [1, 2, 3, 4],
    "col_b": [2, 4, 6, 8],
    "col_c": [3, 6, 9, 12],
    "col_d": [4, 8, 12, 16]
})

df

   col_a  col_b  col_c  col_d
0      1      2      3      4
1      2      4      6      8
2      3      6      9     12
3      4      8     12     16

In [199]:
"""
sql: rows with col b greater than 4

select col_a, col_c
from df
where col_b > 4
"""

df[df['col_b'] > 4][['col_a', 'col_c']]

   col_a  col_c
2      3      9
3      4     12

### get coplumns a and b, filter rows that have `col_c` greater or equal than 9

In SQL:

select
    col_a, 
    col_b,
from df
where col_c >= 9

In [202]:
# filter rows that have `col_c` greater or equal than 9

df[['col_a']][df["col_c"] >= 9]

   col_a
2      3
3      4

We can concatenate conditions in a single instruction:

In [203]:
"""
select *
from df
where col_a div2 and col_d > 8
"""

# rows with even values of `col_a` AND values of `col_d` greater than 8
df[
    (df["col_a"] % 2 == 0) &
    (df["col_d"] > 8)
]

   col_a  col_b  col_c  col_d
3      4      8     12     16

In [ ]:
list(df.columns)

['col_a', 'col_b', 'col_c', 'col_d']

In [ ]:
# filter all the columns that end with "d" 

df[[col for col in df.columns if col.endswith("d")]]

   col_d
0      4
1      8
2     12
3     16

## Adding data to a `pd.DataFrame`

* Adding columns:
```Python
df["new_column"] = data_to_include
```

In [205]:
# create df
df_sport = pd.DataFrame({
    "sport": ["football", "basketball", "rugby"],
    "round_ball": [True, True, False],
    "is_cool": [False, True, True]
})

df_sport

        sport  round_ball  is_cool
0    football        True    False
1  basketball        True     True
2       rugby       False     True

In [208]:
# add a new column called players_per_team
df_sport["players_per_team"] = [11, 5, None]

# print df
df_sport

        sport  round_ball  is_cool  players_per_team
0    football        True    False              11.0
1  basketball        True     True               5.0
2       rugby       False     True               NaN

In [ ]:
df_sport["players_per_team"] = [11, 5, None]

In [ ]:
type(None)

NoneType

In [ ]:
df_sport["players_per_team"].dtype

dtype('float64')

* Adding rows: NOPE
```Python
new_row = {col_1: data_1, col_2: data_2, ..., col_n:data_n}
df = df.append(new_row, ignore_index=True)
```

In [209]:
df_sport = pd.DataFrame({
    "sport": ["football", "basketball", "rugby"],
    "round_ball": [True, True, False],
    "is_cool": [False, True, True]
})

new_row = {
    "sport": "golf",
    "round_ball": True,
    "is_cool": False
}

df = df.append(new_row, ignore_index=True)

df

AttributeError: 'DataFrame' object has no attribute 'append'

In [210]:
# define new row
am_football = [{
    "sport": "american football",
    "round_ball": False,
    "is_cool": False,
    "players_per_team": 11
}]

new_df = pd.DataFrame(am_football)

# add new row for american football using concat
# basically concat is used to add rows with axis=0 (default)
# or columns with axis=1
df = pd.concat([df_sport, new_df]).set_index('sport')

# print df
df

                   round_ball  is_cool  players_per_team
sport
football                 True    False               NaN
basketball               True     True               NaN
rugby                   False     True               NaN
american football       False    False              11.0

In [ ]:
# reverting the screwed up df

df_fixed = df.loc[:, 0:3]

df_fixed.columns = ["sport", "round_ball", "is_cool", "players_per_team"]

df_fixed

        sport  round_ball  is_cool  players_per_team
0    football        True    False                11
1  basketball        True     True                 5
2       rugby       False     True                15

## Practice

### 1. Create the following DataFrame

Save it as the variable `dataset`

| name   | age | type    | is_furry | likes_cats |
|--------|-----|---------|----------|------------|
| dani   | 36  | human   | False    | False      |
| churro | 11   | dog     | True     | False      |
| plant  | 1   | plant   | False    | True       |
| cup    | 1   | object  | False    | True       |

In [ ]:
dataset = pd.DataFrame({
    "name": ['dani', 'churro', 'plant', 'cup'],
    "age": [36, 11, -1, 1],
    "type": ['human', 'dog', 'dead', 'object'],
    "is_furry": [False, True, True, False],
    "likes_cats": [False, False, True, True]
})

dataset

     name  age    type  is_furry  likes_cats
0    dani   36   human     False       False
1  churro   11     dog      True       False
2   plant   -1    dead      True        True
3     cup    1  object     False        True

### 2. Return the value of `is_furry` for the element with `index = 2`

In [ ]:
is_furry = dataset.loc[2, 'is_furry']

is_furry

True

In [ ]:
dataset["is_furry"].values[2]

True

In [ ]:
dataset[["is_furry"]].loc[2]

is_furry    True
Name: 2, dtype: bool

### 3. Add a new column containing the length of the name in characters

In [ ]:
dataset['name_length'] = dataset['name'].map(len)

dataset

,name,age,type,is_furry,likes_cats,logical_op,length_names,name_length
0,dani,36,human,False,False,False,4,4
1,churro,11,dog,True,False,False,4,6
2,plant,-1,dead,True,True,True,4,5
3,cup,1,object,False,True,False,4,3

In [ ]:
dataset['name_length'] = dataset['name'].map(lambda x: len(x))

dataset

,name,age,type,is_furry,likes_cats,logical_op,length_names,name_length
0,dani,36,human,False,False,False,4,4
1,churro,11,dog,True,False,False,4,6
2,plant,-1,dead,True,True,True,4,5
3,cup,1,object,False,True,False,4,3

In [ ]:
# dataset["length_names"] = len(dataset["name"])

names = dataset.loc[:, "name"]

name_length = [len(name) for name in names]

dataset['name_length'] = name_length

dataset

,name,age,type,is_furry,likes_cats,logical_op,length_names,name_length
0,dani,36,human,False,False,False,4,4
1,churro,11,dog,True,False,False,4,6
2,plant,-1,dead,True,True,True,4,5
3,cup,1,object,False,True,False,4,3

### 4. Add a new column named `logical_op` containing the following logical operation:

```Python
`is_furry` and `likes_cats`
```

Keep in mind that logical operators in pandas are not the ones we know (`not`, `and`, `or`) but rather (`~`, `&`, `|`).

Source: https://jakevdp.github.io/PythonDataScienceHandbook/02.06-boolean-arrays-and-masks.html#Boolean-operators

In [ ]:
dataset['logical_op'] = dataset['is_furry'] & dataset['likes_cats']

dataset

     name  age    type  is_furry  likes_cats  logical_op
0    dani   36   human     False       False       False
1  churro   11     dog      True       False       False
2   plant   -1    dead      True        True        True
3     cup    1  object     False        True       False

### 5. Change the `index` from the default to:

`element_1, element_2, element_3, element_4`

In [ ]:
elements = [
    f"element_{i+1}" for i in dataset.index
]

dataset.index = elements

dataset

,name,age,type,is_furry,likes_cats,logical_op,length_names,name_length
element_1,dani,36,human,False,False,False,4,4
element_2,churro,11,dog,True,False,False,4,6
element_3,plant,-1,dead,True,True,True,4,5
element_4,cup,1,object,False,True,False,4,3

### 6. Create a new dataframe called `non_furry` that contains the rows with `is_furry = False`:

In [ ]:
non_furry = dataset[dataset['is_furry']==False]

non_furry

,name,age,type,is_furry,likes_cats,logical_op,length_names,name_length
element_1,dani,36,human,False,False,False,4,4
element_4,cup,1,object,False,True,False,4,3