# Session 15: Reading files into dataframes. Operations on data. Aggregating and grouping.

## Reading files into DataFrames:

`pandas` is a module really versatile when converting data in different files into DataFrames.

We have several functions from `pandas` to read files into DataFrames:
* `pd.read_csv` converts CSV files into a `pd.DataFrame`
* `pd.read_json` converts JSON files into a `pd.DataFrame`
* `pd.read_html` converts HTML files into a `pd.DataFrame`
* `pd.read_clipboard` converts the data in your clipboard into a `pd.DataFrame`
* and many more... https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

In general, `pandas` will read the file just ok, but there are sometimes in which we need to specify some arguments within `read_csv()`:
* separator: `sep` can be semicolon (;), comma (,), tab (\t), etc
* encoding: `encoding` can be `utf-8`, `latin1`, ...

In [84]:
import pandas as pd

In [85]:
import os
os.getcwd()

'/Users/dgh/Desktop/PDA/pda1/class_material'

In [87]:
# lets read animals.csv

animals = pd.read_csv("/Users/dgh/Desktop/PDA/pda1/data/animals.csv", sep=";")

animals.sample(5)

    year             district   dogs  cats
21  2018           ARGANZUELA  10622  4458
91  2015  FUENCARRAL-EL PARDO  18305  2819
63  2016           ARGANZUELA  10591  3202
98  2015            SALAMANCA  13159  1860
97  2015               RETIRO   8883  1391

In [4]:
animals.shape

(126, 4)

In [91]:
wiki = pd.read_clipboard()

In [92]:
wiki

,Country,(or,territory),CIA[2][3],2023–2024,WB[4],2023,UN[5],2005–10,UN[5].1,2010–15,UN[5].2,2015–20
0,(%),Year,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,World,1.17,0.9,1.23,1.19,1.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,*,2.22,2024,2.70,2.78,3.16,2.41,NaN,NaN,NaN,NaN,NaN
3,Albania,*,0.16,2024,-1.10,-0.92,-0.12,0.13,NaN,NaN,NaN,NaN,NaN
4,Algeria,*,1.54,2024,1.60,1.63,1.98,1.67,NaN,NaN,NaN,NaN,NaN
5,Andorra,*,-0.12,2024,0.30,1.37,-1.59,-0.21,NaN,NaN,NaN,NaN,NaN
6,Angola,*,3.33,2024,3.00,3.57,3.52,3.28,NaN,NaN,NaN,NaN,NaN
7,Antigua,and,Barbuda,*,1.11,2024.00,0.60,1.18,1.08,1.01,NaN,NaN,NaN
8,Argentina,*,0.79,2024,0.90,1.04,1.04,0.94,NaN,NaN,NaN,NaN,NaN
9,Armenia,*,-0.42,2024,-0.10,-0.71,0.27,0.15,NaN,NaN,NaN,NaN,NaN
10,Australia,*,1.13,2024,2.40,1.78,1.46,1.30,NaN,NaN,NaN,NaN,NaN

### pandas: `head`, `tail`, `sample`

* `df.head(n)` will display the first n rows of a dataframe. By default, n=5.
* `df.tail(n)` will display the last n rows of a dataframe. By default, n=5.
* `df.sample(n)` will display a random sample of n rows of a dataframe. By default, n=1.

In [94]:
animals.head(11)

    year             district   dogs   cats
0   2019           ARGANZUELA  10556   5074
1   2019              BARAJAS   5086   1515
2   2019          CARABANCHEL  20258   6387
3   2019               CENTRO  16010   9248
4   2019            CHAMARTÍN  11098   3922
5   2019             CHAMBERÍ  13359   4692
6   2019        CIUDAD LINEAL  17286   8183
7   2019  FUENCARRAL-EL PARDO  17375   6121
8   2019            HORTALEZA  15836   8556
9   2019               LATINA  19049  10564
10  2019      MONCLOA-ARAVACA  12367   3931

In [96]:
animals.tail(6)

     year           district   dogs  cats
120  2014           SAN BLAS  12786  2043
121  2014             TETUÁN  12301  2178
122  2014              USERA  11310   978
123  2014          VICÁLVARO   4584   505
124  2014  VILLA DE VALLECAS   7107   940
125  2014         VILLAVERDE  10467   851

In [101]:
animals.sample(5)

    year         district   dogs  cats
47  2017         CHAMBERÍ  13804  3424
31  2018  MONCLOA-ARAVACA  12462  3453
79  2016           TETUÁN  12427  3424
29  2018        HORTALEZA  15965  7797
5   2019         CHAMBERÍ  13359  4692

In [103]:
animals.index

RangeIndex(start=0, stop=126, step=1)

In [102]:
animals.columns

Index(['year', 'district', 'dogs', 'cats'], dtype='object')

## Operations with the data in the columns

With pandas we can not only store tabular-like data, but also perform different operations with it

### Using `pandas` methods and attributes 

Since our columns are nothing `pd.Series` objects, we can use all the attributes and methods that apply to them:
* https://pandas.pydata.org/docs/reference/api/pandas.Series.html

Just a sample of what we can do:
* Attributes:
    * `.index`, `.shape`, `.size`, `.values`, `.T`, 
* Methods:
    * `.abs()`, `.min()`, `.max()`, `.count()`, `.value_counts()`
    * `.sum()`, `.cumsum()`, `.mean()`, `.std()`
    * `.isna()`, `.isnull()`, `.idxmin()`, `.idxmax()`
    * `.unique()`, `.nunique()`, `.drop_duplicates()`

In [10]:
animals.index

RangeIndex(start=0, stop=126, step=1)

In [11]:
animals.shape # tuple with rows and columns

(126, 4)

In [104]:
animals.size # number of cells, also rows * columns

504

In [13]:
animals.values

array([[2019, 'ARGANZUELA', 10556, 5074],
       [2019, 'BARAJAS', 5086, 1515],
       [2019, 'CARABANCHEL', 20258, 6387],
       [2019, 'CENTRO', 16010, 9248],
       [2019, 'CHAMARTÍN', 11098, 3922],
       [2019, 'CHAMBERÍ', 13359, 4692],
       [2019, 'CIUDAD LINEAL', 17286, 8183],
       [2019, 'FUENCARRAL-EL PARDO', 17375, 6121],
       [2019, 'HORTALEZA', 15836, 8556],
       [2019, 'LATINA', 19049, 10564],
       [2019, 'MONCLOA-ARAVACA', 12367, 3931],
       [2019, 'MORATALAZ', 6724, 2502],
       [2019, 'PUENTE DE VALLECAS', 23437, 6208],
       [2019, 'RETIRO', 7786, 3105],
       [2019, 'SALAMANCA', 13471, 5033],
       [2019, 'SAN BLAS', 14228, 5064],
       [2019, 'TETUÁN', 12470, 5535],
       [2019, 'USERA', 12393, 2898],
       [2019, 'VICÁLVARO', 5244, 1505],
       [2019, 'VILLA DE VALLECAS', 9923, 2946],
       [2019, 'VILLAVERDE', 12917, 2694],
       [2018, 'ARGANZUELA', 10622, 4458],
       [2018, 'BARAJAS', 5203, 1300],
       [2018, 'CARABANCHEL', 20265, 5524],
       [2018, 'CENTRO', 15881, 8186],
       [2018, 'CHAMARTÍN', 11417, 3601],
       [2018, 'CHAMBERÍ', 13615, 4087],
       [2018, 'CIUDAD LINEAL', 17375, 7226],
       [2018, 'FUENCARRAL-EL PARDO', 17645, 5558],
       [2018, 'HORTALEZA', 15965, 7797],
       [2018, 'LATINA', 19282, 7990],
       [2018, 'MONCLOA-ARAVACA', 12462, 3453],
       [2018, 'MORATALAZ', 6831, 2279],
       [2018, 'PUENTE DE VALLECAS', 23526, 5138],
       [2018, 'RETIRO', 7955, 2773],
       [2018, 'SALAMANCA', 13312, 4520],
       [2018, 'SAN BLAS', 14202, 4433],
       [2018, 'TETUÁN', 12478, 4763],
       [2018, 'USERA', 12475, 2419],
       [2018, 'VICÁLVARO', 5393, 1279],
       [2018, 'VILLA DE VALLECAS', 9857, 2467],
       [2018, 'VILLAVERDE', 12699, 2307],
       [2017, 'ARGANZUELA', 10808, 3668],
       [2017, 'BARAJAS', 5270, 1064],
       [2017, 'CARABANCHEL', 19964, 4263],
       [2017, 'CENTRO', 15775, 6752],
       [2017, 'CHAMARTÍN', 11894, 3123],
       [2017, 'CHAMBERÍ', 13804, 3424],
       [2017, 'CIUDAD LINEAL', 17799, 6273],
       [2017, 'FUENCARRAL-EL PARDO', 18302, 4760],
       [2017, 'HORTALEZA', 16558, 6748],
       [2017, 'LATINA', 18898, 4708],
       [2017, 'MONCLOA-ARAVACA', 12738, 2776],
       [2017, 'MORATALAZ', 6985, 1909],
       [2017, 'PUENTE DE VALLECAS', 23860, 3961],
       [2017, 'RETIRO', 8309, 2313],
       [2017, 'SALAMANCA', 13205, 3797],
       [2017, 'SAN BLAS', 14206, 3572],
       [2017, 'TETUÁN', 12583, 3851],
       [2017, 'USERA', 12623, 1847],
       [2017, 'VICÁLVARO', 5559, 1009],
       [2017, 'VILLA DE VALLECAS', 9646, 1875],
       [2017, 'VILLAVERDE', 12553, 1737],
       [2016, 'ARGANZUELA', 10591, 3202],
       [2016, 'BARAJAS', 5173, 981],
       [2016, 'CARABANCHEL', 19275, 3728],
       [2016, 'CENTRO', 15470, 6164],
       [2016, 'CHAMARTÍN', 11759, 2809],
       [2016, 'CHAMBERÍ', 13461, 2979],
       [2016, 'CIUDAD LINEAL', 17558, 5774],
       [2016, 'FUENCARRAL-EL PARDO', 17975, 4284],
       [2016, 'HORTALEZA', 16451, 6200],
       [2016, 'LATINA', 18434, 3863],
       [2016, 'MONCLOA-ARAVACA', 12600, 2368],
       [2016, 'MORATALAZ', 6822, 1756],
       [2016, 'PUENTE DE VALLECAS', 23507, 3455],
       [2016, 'RETIRO', 8183, 2061],
       [2016, 'SALAMANCA', 12709, 3424],
       [2016, 'SAN BLAS', 13508, 3170],
       [2016, 'TETUÁN', 12427, 3424],
       [2016, 'USERA', 12430, 1607],
       [2016, 'VICÁLVARO', 5344, 890],
       [2016, 'VILLA DE VALLECAS', 9124, 1575],
       [2016, 'VILLAVERDE', 11969, 1446],
       [2015, 'ARGANZUELA', 9789, 1939],
       [2015, 'BARAJAS', 5217, 663],
       [2015, 'CARABANCHEL', 18031, 2397],
       [2015, 'CENTRO', 13505, 3540],
       [2015, 'CHAMARTÍN', 13159, 1860],
       [2015, 'CHAMBERÍ', 14176, 1939],
       [2015, 'CIUDAD LINEAL', 17882, 4192],
       [2015, 'FUENCARRAL-EL PARDO', 18305, 2819],
       [2015, 'HORTALEZA', 16888, 4927],
       [2015, 'LATINA', 18529, 2595],
       [2015, 'MONCLOA-ARAVACA', 12692, 1578],
       [2015, 'MORATALAZ', 6881, 1173],
       [2015, 'PUENTE DE VALLECAS', 22765, 2117],
       [2015, 'RETIRO', 8883, 1391],
       [2015, 'SALAMANCA', 13159, 1860],
       [2015, 'SAN BLAS', 13067, 2188],
       [2015, 'TETUÁN', 12502, 2204],
       [2015, 'USERA', 11641, 992],
       [2015, 'VICÁLVARO', 4702, 545],
       [2015, 'VILLA DE VALLECAS', 7416, 975],
       [2015, 'VILLAVERDE', 11092, 897],
       [2014, 'ARGANZUELA', 9595, 1853],
       [2014, 'BARAJAS', 5233, 659],
       [2014, 'CARABANCHEL', 17525, 2360],
       [2014, 'CENTRO', 13285, 3460],
       [2014, 'CHAMARTÍN', 12942, 1793],
       [2014, 'CHAMBERÍ', 13869, 1902],
       [2014, 'CIUDAD LINEAL', 17604, 3042],
       [2014, 'FUENCARRAL EL PARDO', 18033, 2790],
       [2014, 'HORTALEZA', 16476, 4761],
       [2014, 'LATINA', 18106, 2533],
       [2014, 'MONCLOA-ARAVACA', 12398, 1548],
       [2014, 'MORATALAZ', 6706, 1153],
       [2014, 'PUENTE DE VALLECAS', 22072, 2065],
       [2014, 'RETIRO', 8774, 1344],
       [2014, 'SALAMANCA', 12942, 1793],
       [2014, 'SAN BLAS', 12786, 2043],
       [2014, 'TETUÁN', 12301, 2178],
       [2014, 'USERA', 11310, 978],
       [2014, 'VICÁLVARO', 4584, 505],
       [2014, 'VILLA DE VALLECAS', 7107, 940],
       [2014, 'VILLAVERDE', 10467, 851]], dtype=object)

In [14]:
animals.T

,0,1,2,3,4,5,6,7,8,9,...,116,117,118,119,120,121,122,123,124,125
year,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,...,2014,2014,2014,2014,2014,2014,2014,2014,2014,2014
district,ARGANZUELA,BARAJAS,CARABANCHEL,CENTRO,CHAMARTÍN,CHAMBERÍ,CIUDAD LINEAL,FUENCARRAL-EL PARDO,HORTALEZA,LATINA,...,MORATALAZ,PUENTE DE VALLECAS,RETIRO,SALAMANCA,SAN BLAS,TETUÁN,USERA,VICÁLVARO,VILLA DE VALLECAS,VILLAVERDE
dogs,10556,5086,20258,16010,11098,13359,17286,17375,15836,19049,...,6706,22072,8774,12942,12786,12301,11310,4584,7107,10467
cats,5074,1515,6387,9248,3922,4692,8183,6121,8556,10564,...,1153,2065,1344,1793,2043,2178,978,505,940,851

#### abs

In [105]:
my_list = [1, -4, 5, 6]

[abs(x) for x in my_list]

[1, 4, 5, 6]

In [16]:
list(map(abs, my_list))

[1, 4, 5, 6]

In [107]:
animals["dogs"].abs()

0      10556
1       5086
2      20258
3      16010
4      11098
       ...
121    12301
122    11310
123     4584
124     7107
125    10467
Name: dogs, Length: 126, dtype: int64

#### max, min, count, value_counts

In [111]:
pd.Series(['a1', 'abc', 'a2aa']).min()

'a1'

In [112]:
# max value in series
animals["dogs"].max()

23860

In [19]:
# min value in series
animals["dogs"].min()

4584

In [20]:
# number of elements in series
animals["district"].count()

126

In [113]:
animals["district"].unique() # distinct

array(['ARGANZUELA', 'BARAJAS', 'CARABANCHEL', 'CENTRO', 'CHAMARTÍN',
       'CHAMBERÍ', 'CIUDAD LINEAL', 'FUENCARRAL-EL PARDO', 'HORTALEZA',
       'LATINA', 'MONCLOA-ARAVACA', 'MORATALAZ', 'PUENTE DE VALLECAS',
       'RETIRO', 'SALAMANCA', 'SAN BLAS', 'TETUÁN', 'USERA', 'VICÁLVARO',
       'VILLA DE VALLECAS', 'VILLAVERDE', 'FUENCARRAL EL PARDO'],
      dtype=object)

In [114]:
animals["district"].nunique() # count(distinct ...)

22

In [23]:
animals["district"].size

126

In [24]:
animals["district"].shape

(126,)

In [25]:
animals

     year           district   dogs  cats
0    2019         ARGANZUELA  10556  5074
1    2019            BARAJAS   5086  1515
2    2019        CARABANCHEL  20258  6387
3    2019             CENTRO  16010  9248
4    2019          CHAMARTÍN  11098  3922
..    ...                ...    ...   ...
121  2014             TETUÁN  12301  2178
122  2014              USERA  11310   978
123  2014          VICÁLVARO   4584   505
124  2014  VILLA DE VALLECAS   7107   940
125  2014         VILLAVERDE  10467   851

[126 rows x 4 columns]

In [116]:
# counts items per category
animals["year"].value_counts(normalize=True)

year
2019    0.166667
2018    0.166667
2017    0.166667
2016    0.166667
2015    0.166667
2014    0.166667
Name: proportion, dtype: float64

In [117]:
"""
select year, count(distinct year)
from df
group by year
"""

animals["year"].value_counts()

year
2019    21
2018    21
2017    21
2016    21
2015    21
2014    21
Name: count, dtype: int64

In [28]:
# if we pass normalize=True to `value_counts` we will get the proportions instead of the totals
s = animals["district"].value_counts(normalize=True)

s.round(3).sort_index(ascending=True)

district
ARGANZUELA             0.048
BARAJAS                0.048
CARABANCHEL            0.048
CENTRO                 0.048
CHAMARTÍN              0.048
CHAMBERÍ               0.048
CIUDAD LINEAL          0.048
FUENCARRAL EL PARDO    0.008
FUENCARRAL-EL PARDO    0.040
HORTALEZA              0.048
LATINA                 0.048
MONCLOA-ARAVACA        0.048
MORATALAZ              0.048
PUENTE DE VALLECAS     0.048
RETIRO                 0.048
SALAMANCA              0.048
SAN BLAS               0.048
TETUÁN                 0.048
USERA                  0.048
VICÁLVARO              0.048
VILLA DE VALLECAS      0.048
VILLAVERDE             0.048
Name: proportion, dtype: float64

#### sum, cumsum, mean, std

In [119]:
pd.Series([[1, 2], [2, 3], [3, 4]]).sum()

[1, 2, 2, 3, 3, 4]

In [29]:
# sum of all elements
animals["cats"].sum()

419173

In [30]:
# cummulative sum 
# item1, item1+item2, item1+item2+item3, ...
animals["cats"].cumsum()

0        5074
1        6589
2       12976
3       22224
4       26146
        ...
121    415899
122    416877
123    417382
124    418322
125    419173
Name: cats, Length: 126, dtype: int64

In [31]:
# mean value of series
animals["cats"].mean()

3326.7698412698414

In [32]:
# standard deviation of series
animals["cats"].std()

2062.750967665068

In [33]:
animals.describe()

              year          dogs          cats
count   126.000000    126.000000    126.000000
mean   2016.500000  13062.206349   3326.769841
std       1.714643   4670.823654   2062.750968
min    2014.000000   4584.000000    505.000000
25%    2015.000000  10059.000000   1848.500000
50%    2016.500000  12723.500000   2814.000000
75%    2018.000000  16537.500000   4451.750000
max    2019.000000  23860.000000  10564.000000

#### isna/isnull, idxmin/idxmax

In [34]:
import numpy as np

In [121]:
# missing values in pandas are indicated as NaN
# with isna we can check how many 

s = pd.Series([1, None, "a", True, np.nan])

s[s.isnull()] # return all the values that are not null

1    None
4     NaN
dtype: object

In [36]:
# isna: returns array with same shape with True/False to mask NaN
animals["dogs"].isna().sum()

0

In [37]:
animals.isna().mean()

year        0.0
district    0.0
dogs        0.0
cats        0.0
dtype: float64

In [ ]:
# with dropna we can drop rows with NaN
pd.Series([1, None, "a", True, np.nan]).dropna()

0       1
2       a
3    True
dtype: object

In [39]:
animals.isna().mean()

year        0.0
district    0.0
dogs        0.0
cats        0.0
dtype: float64

`idxmax` and `idxmin` return the index of the first occurrence of the maximum or minimum value in a Series/column in a DataFrame.

In [122]:
# idxmax() returns the row label (index) of the highest value in series
animals#.iloc[animals["dogs"].idxmax(), :]

     year           district   dogs  cats
0    2019         ARGANZUELA  10556  5074
1    2019            BARAJAS   5086  1515
2    2019        CARABANCHEL  20258  6387
3    2019             CENTRO  16010  9248
4    2019          CHAMARTÍN  11098  3922
..    ...                ...    ...   ...
121  2014             TETUÁN  12301  2178
122  2014              USERA  11310   978
123  2014          VICÁLVARO   4584   505
124  2014  VILLA DE VALLECAS   7107   940
125  2014         VILLAVERDE  10467   851

[126 rows x 4 columns]

In [125]:
# what was the year in which the maximum amount of dogs happened in Madrid

"""
select
    year
from animals
where dogs in (select max(dogs) from animals)
"""

animals.loc[animals["dogs"].idxmax(), 'year']

2017

In [126]:
animals.iloc[animals["dogs"].idxmax(), 0]

2017

In [42]:
# what's the district with more cats in all the period

''' select
    district,
    sum(cats) as sum_cats,
from animals
group by district
having sum(cats) = (select max(sum(cats) from animals group by district)) '''

' select\n    district,\n    sum(cats) as sum_cats,\nfrom animals\ngroup by district\nhaving sum(cats) = (select max(sum(cats) from animals group by district)) '

In [43]:
pd.Series([3, 3, 2]).idxmax()

0

In [44]:
animals.iloc[animals["dogs"].idxmin(), :]

year             2014
district    VICÁLVARO
dogs             4584
cats              505
Name: 123, dtype: object

In [45]:
# idxmin() returns the row label (index) of the lowest value in series
animals["dogs"].idxmin()

123

#### unique, nunique, drop_duplicates

In [128]:
# returns an array with the unique values, like doing set(series)
animals["district"].nunique()

22

In [47]:
animals["year"].unique()

array([2019, 2018, 2017, 2016, 2015, 2014])

In [48]:
# nunique returns how many unique elements there are in the series, like doing len(set(series))
animals["year"].nunique()

6

In [49]:
animals["year"].value_counts()

year
2019    21
2018    21
2017    21
2016    21
2015    21
2014    21
Name: count, dtype: int64

In [ ]:
# drop_duplicates returns a series with only the unique values and the index at which they are
animals.drop_duplicates(subset=["year", "district"], inplace=True)

NoneType

In [51]:
animals

     year           district   dogs  cats
0    2019         ARGANZUELA  10556  5074
1    2019            BARAJAS   5086  1515
2    2019        CARABANCHEL  20258  6387
3    2019             CENTRO  16010  9248
4    2019          CHAMARTÍN  11098  3922
..    ...                ...    ...   ...
121  2014             TETUÁN  12301  2178
122  2014              USERA  11310   978
123  2014          VICÁLVARO   4584   505
124  2014  VILLA DE VALLECAS   7107   940
125  2014         VILLAVERDE  10467   851

[126 rows x 4 columns]

### Create new columns out of existing columns

* We can operate 2 or more columns with arithmetic operators
* We can perform logical operations in columns using np.where
    * ```Python
    np.where(condition_on_column, result_if_true, result_if_false)
    ```

In [ ]:
select
    *,
    cats + dogs as total_animals
from animals

In [132]:
# sum two columns

animals["total_animals"] = animals["cats"] + animals["dogs"]

animals.head()

   year     district   dogs  cats  total_animals
0  2019   ARGANZUELA  10556  5074          15630
1  2019      BARAJAS   5086  1515           6601
2  2019  CARABANCHEL  20258  6387          26645
3  2019       CENTRO  16010  9248          25258
4  2019    CHAMARTÍN  11098  3922          15020

In [ ]:
animals["dogs_squared"] = 0 # animals["dogs"] ** 2

### np.where

```Python
np.where(
    condition_to_check,
    value_if_condition_is_true,
    value_if_condition_is_false
)
```

equivalent to 

```python
if condition:
    value_if_condition_is_true
else:
    value_if_condition_is_false
```

In [ ]:
# create a new column based on a logical condition on an existing column: `np.where`

import numpy as np

mean_animals = animals["total_animals"].mean()
print(mean_animals)

animals["total_animals_categorical"] = np.where(
    animals["total_animals"] > mean_animals, #if animals above mean
    "above_mean", # save "above_mean"
    1 # save "below_mean"
)

animals.sample(5)

16388.97619047619

,year,district,dogs,cats,total_animals,total_animals_categorical
89,2015,CHAMBERÍ,14176,1939,16115,below_mean
46,2017,CHAMARTÍN,11894,3123,15017,below_mean
0,2019,ARGANZUELA,10556,5074,15630,below_mean
103,2015,VILLA DE VALLECAS,7416,975,8391,below_mean
125,2014,VILLAVERDE,10467,851,11318,below_mean

In [137]:
new_animals = animals.copy()

new_animals.drop(125, axis=0)

,year,district,dogs,cats,total_animals,total_animals_categorical
0,2019,ARGANZUELA,10556,5074,15630,below_mean
1,2019,BARAJAS,5086,1515,6601,below_mean
2,2019,CARABANCHEL,20258,6387,26645,above_mean
3,2019,CENTRO,16010,9248,25258,above_mean
4,2019,CHAMARTÍN,11098,3922,15020,below_mean
...,...,...,...,...,...,...
120,2014,SAN BLAS,12786,2043,14829,below_mean
121,2014,TETUÁN,12301,2178,14479,below_mean
122,2014,USERA,11310,978,12288,below_mean
123,2014,VICÁLVARO,4584,505,5089,below_mean
124,2014,VILLA DE VALLECAS,7107,940,8047,below_mean

In [56]:
# concatenating strings and converting
animals["concat_string"] = animals["year"].astype(str) + " - " + animals["district"]

animals

,year,district,dogs,cats,total_animals,dogs_squared,total_animals_categorical,concat_string
0,2019,ARGANZUELA,10556,5074,15630,111429136,below_mean,2019 - ARGANZUELA
1,2019,BARAJAS,5086,1515,6601,25867396,below_mean,2019 - BARAJAS
2,2019,CARABANCHEL,20258,6387,26645,410386564,above_mean,2019 - CARABANCHEL
3,2019,CENTRO,16010,9248,25258,256320100,above_mean,2019 - CENTRO
4,2019,CHAMARTÍN,11098,3922,15020,123165604,below_mean,2019 - CHAMARTÍN
...,...,...,...,...,...,...,...,...
121,2014,TETUÁN,12301,2178,14479,151314601,below_mean,2014 - TETUÁN
122,2014,USERA,11310,978,12288,127916100,below_mean,2014 - USERA
123,2014,VICÁLVARO,4584,505,5089,21013056,below_mean,2014 - VICÁLVARO
124,2014,VILLA DE VALLECAS,7107,940,8047,50509449,below_mean,2014 - VILLA DE VALLECAS
125,2014,VILLAVERDE,10467,851,11318,109558089,below_mean,2014 - VILLAVERDE

In [57]:
# create a new column called "cats_per_dog" that contains the ratio cats/dogs
animals["cats_per_dog"] = animals["cats"] / animals["dogs"]

animals.iloc[animals["cats_per_dog"].idxmax(), :]

year                                  2019
district                            CENTRO
dogs                                 16010
cats                                  9248
total_animals                        25258
dogs_squared                     256320100
total_animals_categorical       above_mean
concat_string                2019 - CENTRO
cats_per_dog                      0.577639
Name: 3, dtype: object

In [58]:
# create a new column called "cum_sum_animals" that contains 
# the cummulative sum of the total animals 
animals["cum_sum_animals"] = animals["total_animals"].cumsum()

animals.tail()

,year,district,dogs,cats,total_animals,dogs_squared,total_animals_categorical,concat_string,cats_per_dog,cum_sum_animals
121,2014,TETUÁN,12301,2178,14479,151314601,below_mean,2014 - TETUÁN,0.177059,2028269
122,2014,USERA,11310,978,12288,127916100,below_mean,2014 - USERA,0.086472,2040557
123,2014,VICÁLVARO,4584,505,5089,21013056,below_mean,2014 - VICÁLVARO,0.110166,2045646
124,2014,VILLA DE VALLECAS,7107,940,8047,50509449,below_mean,2014 - VILLA DE VALLECAS,0.132264,2053693
125,2014,VILLAVERDE,10467,851,11318,109558089,below_mean,2014 - VILLAVERDE,0.081303,2065011

### Sorting columns using `.sort_values()`

We can sort our dataframes this way:

```Python
df.sort_values(by=[columns_to_order_with], ascending=True)
```

In [ ]:
animals.sort_values(by="cats", ascending=True)

,year,district,dogs,cats,total_animals,total_animals_categorical
9,2019,LATINA,19049,10564,29613,above_mean
3,2019,CENTRO,16010,9248,25258,above_mean
8,2019,HORTALEZA,15836,8556,24392,above_mean
24,2018,CENTRO,15881,8186,24067,above_mean
6,2019,CIUDAD LINEAL,17286,8183,25469,above_mean
...,...,...,...,...,...,...
125,2014,VILLAVERDE,10467,851,11318,below_mean
85,2015,BARAJAS,5217,663,5880,below_mean
106,2014,BARAJAS,5233,659,5892,below_mean
102,2015,VICÁLVARO,4702,545,5247,below_mean
123,2014,VICÁLVARO,4584,505,5089,below_mean

In [60]:
animals.sort_values(by=["cats", "dogs"], ascending=[True, False])

,year,district,dogs,cats,total_animals,dogs_squared,total_animals_categorical,concat_string,cats_per_dog,cum_sum_animals
123,2014,VICÁLVARO,4584,505,5089,21013056,below_mean,2014 - VICÁLVARO,0.110166,2045646
102,2015,VICÁLVARO,4702,545,5247,22108804,below_mean,2015 - VICÁLVARO,0.115908,1739965
106,2014,BARAJAS,5233,659,5892,27384289,below_mean,2014 - BARAJAS,0.125932,1777685
85,2015,BARAJAS,5217,663,5880,27217089,below_mean,2015 - BARAJAS,0.127085,1464881
125,2014,VILLAVERDE,10467,851,11318,109558089,below_mean,2014 - VILLAVERDE,0.081303,2065011
...,...,...,...,...,...,...,...,...,...,...
6,2019,CIUDAD LINEAL,17286,8183,25469,298805796,above_mean,2019 - CIUDAD LINEAL,0.473389,132674
24,2018,CENTRO,15881,8186,24067,252206161,above_mean,2018 - CENTRO,0.515459,453995
8,2019,HORTALEZA,15836,8556,24392,250778896,above_mean,2019 - HORTALEZA,0.540288,180562
3,2019,CENTRO,16010,9248,25258,256320100,above_mean,2019 - CENTRO,0.577639,74134
9,2019,LATINA,19049,10564,29613,362864401,above_mean,2019 - LATINA,0.554570,210175

In [61]:
animals.sort_values(by=["cats", "dogs"], ascending=[False, True])

,year,district,dogs,cats,total_animals,dogs_squared,total_animals_categorical,concat_string,cats_per_dog,cum_sum_animals
9,2019,LATINA,19049,10564,29613,362864401,above_mean,2019 - LATINA,0.554570,210175
3,2019,CENTRO,16010,9248,25258,256320100,above_mean,2019 - CENTRO,0.577639,74134
8,2019,HORTALEZA,15836,8556,24392,250778896,above_mean,2019 - HORTALEZA,0.540288,180562
24,2018,CENTRO,15881,8186,24067,252206161,above_mean,2018 - CENTRO,0.515459,453995
6,2019,CIUDAD LINEAL,17286,8183,25469,298805796,above_mean,2019 - CIUDAD LINEAL,0.473389,132674
...,...,...,...,...,...,...,...,...,...,...
125,2014,VILLAVERDE,10467,851,11318,109558089,below_mean,2014 - VILLAVERDE,0.081303,2065011
85,2015,BARAJAS,5217,663,5880,27217089,below_mean,2015 - BARAJAS,0.127085,1464881
106,2014,BARAJAS,5233,659,5892,27384289,below_mean,2014 - BARAJAS,0.125932,1777685
102,2015,VICÁLVARO,4702,545,5247,22108804,below_mean,2015 - VICÁLVARO,0.115908,1739965
123,2014,VICÁLVARO,4584,505,5089,21013056,below_mean,2014 - VICÁLVARO,0.110166,2045646

## Practice

### Exercise 1:
Whats the percentage that represents the dogs in "LATINA" in 2018 compared to the whole city in 2018

In [160]:
animals[
    (animals['year']==2018)
]['dogs'].sum()

278460

In [153]:
dogs_latina_2018 = animals[
    (animals['year']==2018) & (animals['district']=='LATINA')
]['dogs'].values[0]

dogs_2018 = animals[
    (animals['year']==2018)
]['dogs'].sum()

dogs_latina_2018 / dogs_2018

0.06924513395101631

In [ ]:
dogs_latina_2018 = animals[
    # (animals['year']==2018)
    (animals['year'].isin([2018]))
]['dogs'].values[0]

### Exercise 2:
How many districts had an "above_mean" rating in 2016?

In [ ]:
select
    count(*)
from animals
where total_animals_categorical = 'above_mean'

In [172]:
animals[
    (animals['total_animals_categorical'] == 'above_mean')
    & (animals['year'] == 2016)
].shape[0]

9

### Exercise 3:
Has the "Hortaleza" district increased or decreased its dog population in the analyzed period? By how much?

In [189]:
dogs_hort_2019 = animals[
    (animals['district'] == 'HORTALEZA')
]['dogs'].values[0]

dogs_hort_2014 = animals[
    (animals['district'] == 'HORTALEZA')
]['dogs'].values[-1]

abs(dogs_hort_2019 - dogs_hort_2014)

640

## Groupby and aggregations

### `groupby`

Just like in SQL, we can use `groupby` to perform operations to whole groups on our DataFrames.

```Python
df.groupby([columns_to_group]).function_to_apply_to_each_group
```

In [190]:
import pandas as pd

animals = pd.read_csv('../data/animals.csv', sep=';')

animals.head()

   year     district   dogs  cats
0  2019   ARGANZUELA  10556  5074
1  2019      BARAJAS   5086  1515
2  2019  CARABANCHEL  20258  6387
3  2019       CENTRO  16010  9248
4  2019    CHAMARTÍN  11098  3922

In [191]:
# how many dogs per year
"""
select
    year,
    sum(dogs) as sum_dogs,
from animals
group by year
"""

animals.groupby("year")[["dogs"]].sum()

        dogs
year
2014  264115
2015  270281
2016  274770
2017  281339
2018  278460
2019  276873

In [69]:
# read energy data
from datetime import datetime

energy = pd.read_csv("../data/energy.csv")

energy.head()

,datetime,power_demand,nuclear,gas,solar,hydro,coal,wind,spot_price,year,month,day,hour,weekday
0,2018-12-31 23:00:00+00:00,23251.2,6059.2,2954.0,7.1,3202.8,1867.0,3830.3,66.88,2018,12,31,23,0
1,2019-01-01 00:00:00+00:00,22485.0,6059.2,3044.1,8.0,2884.4,1618.0,3172.1,66.88,2019,1,1,0,1
2,2019-01-01 01:00:00+00:00,20977.0,6059.2,3138.6,7.5,1950.8,1535.3,2980.5,66.00,2019,1,1,1,1
3,2019-01-01 02:00:00+00:00,19754.2,6059.2,3596.2,7.5,1675.7,1344.0,2840.0,63.64,2019,1,1,2,1
4,2019-01-01 03:00:00+00:00,19320.6,6063.4,3192.6,7.5,1581.8,1345.0,3253.4,58.85,2019,1,1,3,1

In [70]:
energy[["power_demand"]].head()

   power_demand
0       23251.2
1       22485.0
2       20977.0
3       19754.2
4       19320.6

In [193]:
# mean spot_price per month 

"""
select 
    month,
    avg(spot_price)
from energy
group by month
"""

energy.groupby("month", as_index=False)[["spot_price"]].mean()

    month  spot_price
0       1   61.959852
1       2   54.020491
2       3   48.836116
3       4   50.403611
4       5   48.393992
5       6   47.161236
6       7   51.464301
7       8   44.951815
8       9   42.130111
9      10   47.152325
10     11   42.187181
11     12   33.700555

In [194]:
# max power_demand per hour

"""
select
    hour, 
    max(power_demand)
from energy
group by 1
"""


max_energy_per_hour = energy.groupby("hour")[["power_demand"]].max()

max_energy_per_hour

      power_demand
hour
0          27739.0
1          26459.4
2          26298.4
3          26429.5
4          28167.9
5          30511.2
6          34706.4
7          38116.0
8          39241.7
9          39898.3
10         39289.1
11         39933.2
12         39467.0
13         39077.4
14         39077.4
15         38950.0
16         38195.1
17         38771.1
18         39825.8
19         40094.8
20         39086.9
21         36312.2
22         32993.1
23         30124.9

In [73]:
energy.idxmin()

datetime           0
power_demand    8597
nuclear         7487
gas             2296
solar            360
hydro           6866
coal            8374
wind            6490
spot_price      8572
year               0
month              1
day                1
hour               1
weekday            0
dtype: int64

In [195]:
energy.head()

,datetime,power_demand,nuclear,gas,solar,hydro,coal,wind,spot_price,year,month,day,hour,weekday,fossil_fuel_consumption
0,2018-12-31 23:00:00+00:00,23251.2,6059.2,2954.0,7.1,3202.8,1867.0,3830.3,66.88,2018,12,31,23,0,4821.0
1,2019-01-01 00:00:00+00:00,22485.0,6059.2,3044.1,8.0,2884.4,1618.0,3172.1,66.88,2019,1,1,0,1,4662.1
2,2019-01-01 01:00:00+00:00,20977.0,6059.2,3138.6,7.5,1950.8,1535.3,2980.5,66.00,2019,1,1,1,1,4673.9
3,2019-01-01 02:00:00+00:00,19754.2,6059.2,3596.2,7.5,1675.7,1344.0,2840.0,63.64,2019,1,1,2,1,4940.2
4,2019-01-01 03:00:00+00:00,19320.6,6063.4,3192.6,7.5,1581.8,1345.0,3253.4,58.85,2019,1,1,3,1,4537.6

In [197]:
# day of week with lowest average consumption of fossil fuels 

energy["fossil_fuel_consumption"] = energy["gas"] + energy["coal"]

mean_fuel_consumption = energy.groupby(["weekday"])[["fossil_fuel_consumption"]].mean()

mean_fuel_consumption.idxmin()

fossil_fuel_consumption    6
dtype: int64

### Inside a `groupby` object

`groupby` creates a tuple per `category` in the `column`(s) we're grouping by:
* The first element of the tuple is each one of the `category` in `column`
* The second element is the data associated to that category:
    * ```Python
    df[df[col_groupby]==category]
    ```

In [203]:
# what's inside a groupby object?
list(energy.groupby("year"))[1][1]

,datetime,power_demand,nuclear,gas,solar,hydro,coal,wind,spot_price,year,month,day,hour,weekday,fossil_fuel_consumption
1,2019-01-01 00:00:00+00:00,22485.0,6059.2,3044.1,8.0,2884.4,1618.0,3172.1,66.88,2019,1,1,0,1,4662.1
2,2019-01-01 01:00:00+00:00,20977.0,6059.2,3138.6,7.5,1950.8,1535.3,2980.5,66.00,2019,1,1,1,1,4673.9
3,2019-01-01 02:00:00+00:00,19754.2,6059.2,3596.2,7.5,1675.7,1344.0,2840.0,63.64,2019,1,1,2,1,4940.2
4,2019-01-01 03:00:00+00:00,19320.6,6063.4,3192.6,7.5,1581.8,1345.0,3253.4,58.85,2019,1,1,3,1,4537.6
5,2019-01-01 04:00:00+00:00,19262.3,6063.4,3167.9,7.5,1535.6,1377.5,3234.0,55.47,2019,1,1,4,1,4545.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8732,2019-12-30 19:00:00+00:00,31160.6,7106.3,4400.0,0.1,7910.8,685.0,2013.5,47.50,2019,12,30,19,0,5085.0
8733,2019-12-30 20:00:00+00:00,31152.9,7106.3,4832.3,NaN,7517.6,681.0,2096.7,46.42,2019,12,30,20,0,5513.3
8734,2019-12-30 21:00:00+00:00,29151.0,7105.3,4467.0,NaN,7080.2,698.0,2028.3,42.76,2019,12,30,21,0,5165.0
8735,2019-12-30 22:00:00+00:00,26989.6,7107.2,4672.2,NaN,6716.1,626.0,2031.8,40.88,2019,12,30,22,0,5298.2
8736,2019-12-30 23:00:00+00:00,24350.5,7099.0,3765.9,NaN,6403.5,528.0,1927.2,37.55,2019,12,30,23,0,4293.9

In [76]:
groupby_object = energy.groupby("year")

In [77]:
# first element
list(groupby_object)[1][1]["year"].unique()

array([2019])

In [78]:
# category
list(groupby_object)[0][0]

2018

In [79]:
# data associated with category
list(groupby_object)[0][1]

,datetime,power_demand,nuclear,gas,solar,hydro,coal,wind,spot_price,year,month,day,hour,weekday,fossil_fuel_consumption
0,2018-12-31 23:00:00+00:00,23251.2,6059.2,2954.0,7.1,3202.8,1867.0,3830.3,66.88,2018,12,31,23,0,4821.0

Now we understand the `groupby` object, we can dig a bit deeper into the syntax

If we want to groupby several columns, we can pass a list of columns to `groupby` and perform the operation we need.

If we don't want the columns to become the index of the resulting DF, we can pass `as_index=False` to `groupby`

In [ ]:
"""
select
    year,
    sum(price) as sum_price,
    avg(solar) as avg_solar
from energy
group by year
"""

### `groupby` and `agg`

If we want to perform different operations after `groupby` we can mix `groupby` and `agg`.

In [204]:
energy.head()

,datetime,power_demand,nuclear,gas,solar,hydro,coal,wind,spot_price,year,month,day,hour,weekday,fossil_fuel_consumption
0,2018-12-31 23:00:00+00:00,23251.2,6059.2,2954.0,7.1,3202.8,1867.0,3830.3,66.88,2018,12,31,23,0,4821.0
1,2019-01-01 00:00:00+00:00,22485.0,6059.2,3044.1,8.0,2884.4,1618.0,3172.1,66.88,2019,1,1,0,1,4662.1
2,2019-01-01 01:00:00+00:00,20977.0,6059.2,3138.6,7.5,1950.8,1535.3,2980.5,66.00,2019,1,1,1,1,4673.9
3,2019-01-01 02:00:00+00:00,19754.2,6059.2,3596.2,7.5,1675.7,1344.0,2840.0,63.64,2019,1,1,2,1,4940.2
4,2019-01-01 03:00:00+00:00,19320.6,6063.4,3192.6,7.5,1581.8,1345.0,3253.4,58.85,2019,1,1,3,1,4537.6

In [ ]:
energy.head(2)

,datetime,power_demand,nuclear,gas,solar,hydro,coal,wind,spot_price,year,month,day,hour,weekday,fossil_fuel_consumption
0,2018-12-31 23:00:00+00:00,23251.2,6059.2,2954.0,7.1,3202.8,1867.0,3830.3,66.88,2018,12,31,23,0,4821.0
1,2019-01-01 00:00:00+00:00,22485.0,6059.2,3044.1,8.0,2884.4,1618.0,3172.1,66.88,2019,1,1,0,1,4662.1

In [ ]:
energy["power_demand"]

0       23251.2
1       22485.0
2       20977.0
3       19754.2
4       19320.6
         ...
8732    31160.6
8733    31152.9
8734    29151.0
8735    26989.6
8736    24350.5
Name: power_demand, Length: 8737, dtype: float64

In [212]:
# extract the min, max and mean spot_price per day, and sum and std of hydro per day

"""
select
    day,
    min(spot_price),
    max(spot_price),
    mean(spot_price),
    sum(hydro),
    std(hydro)
from energy
group by day
"""

df = energy.groupby("day")[["hydro", "spot_price"]].agg(
    {
        "spot_price": ["min", "max", "mean"],
        "hydro": ["sum", "std"]
    }
)

# mean spot_price on day 6th
print(df.columns)
df.loc[[6, 7], ('spot_price',  'min')]

MultiIndex([('spot_price',  'min'),
            ('spot_price',  'max'),
            ('spot_price', 'mean'),
            (     'hydro',  'sum'),
            (     'hydro',  'std')],
           )

day
6    25.68
7    26.73
Name: (spot_price, min), dtype: float64

In [ ]:
df.iloc[5, 2]

47.40774305555556

In [ ]:
import numpy as np

df = energy.groupby("day")[["hydro", "spot_price"]].agg(
    {
        "spot_price": ["min", "max", "mean"],
#        "hydro": ["sum", "std"]
    }
)

df.head()

    spot_price
           min    max       mean
day
1        27.31  68.07  48.912049
2        16.45  69.30  46.173125
3         6.20  71.10  47.402361
4         3.52  71.94  49.242986
5         8.45  69.50  48.337986

In [ ]:
df[('spot_price', 'mean')]

day
1     48.912049
2     46.173125
3     47.402361
4     49.242986
5     48.337986
6     47.407743
7     48.625451
8     48.119132
9     48.044063
10    46.376111
11    49.112674
12    48.225729
13    47.233333
14    47.478264
15    48.465069
16    49.890069
17    47.238160
18    49.840313
19    47.573646
20    46.326944
21    46.755729
22    46.909514
23    46.642118
24    45.106736
25    44.222049
26    46.325972
27    47.056076
28    48.337222
29    49.116288
30    49.551553
31    50.491931
Name: (spot_price, mean), dtype: float64

In [ ]:
df.columns

MultiIndex([('spot_price',  'min'),
            ('spot_price',  'max'),
            ('spot_price', 'mean')],
           )

In [ ]:
# change the names of the columns

df.columns = [f"{tpl[0]}_{tpl[1]}" for tpl in df.columns]

df

     spot_price_min  spot_price_max  spot_price_mean
day
1             27.31           68.07        48.912049
2             16.45           69.30        46.173125
3              6.20           71.10        47.402361
4              3.52           71.94        49.242986
5              8.45           69.50        48.337986
6             25.68           68.00        47.407743
7             26.73           70.39        48.625451
8             27.10           70.00        48.119132
9             28.61           69.01        48.044063
10            15.60           69.75        46.376111
11            26.00           70.45        49.112674
12            21.01           69.69        48.225729
13             6.25           71.69        47.233333
14            19.64           72.52        47.478264
15             5.41           74.74        48.465069
16            29.19           72.99        49.890069
17             5.48           73.45        47.238160
18            15.00           72.01        49.840313
19             2.27           70.00        47.573646
20             1.76           70.11        46.326944
21             0.51           73.90        46.755729
22             0.10           71.20        46.909514
23             1.00           68.89        46.642118
24             0.03           70.13        45.106736
25             4.00           69.69        44.222049
26             3.92           68.50        46.325972
27            16.60           64.18        47.056076
28            12.56           70.01        48.337222
29            20.97           68.07        49.116288
30            21.47           68.65        49.551553
31            38.10           66.88        50.491931

In [ ]:
# groupby on several columns and perform mean and sum on coal and wind

df = energy.groupby(["month", "weekday", "hour"]).agg({
    "coal": ["sum", "mean", "std"],
    "wind": ["min", "max", "std"],
    "solar": ["min", "max", "std"],
})

df

                       coal                              wind           \
                        sum         mean          std     min      max
month weekday hour
1     0       0     11913.6  2978.400000  1548.304216  6924.0  12154.0
              1     11402.2  2850.550000  1527.859214  6895.5  12342.0
              2     11539.3  2884.825000  1519.787021  6949.7  12765.9
              3     11753.1  2938.275000  1437.644823  7174.2  12892.9
              4     12982.3  3245.575000  1554.457964  7290.8  13219.6
...                     ...          ...          ...     ...      ...
12    6       19     2312.1   770.700000   323.748251  2025.4  13660.9
              20     2302.1   767.366667   324.047471  2026.8  13323.1
              21     2288.1   572.025000   422.352747  2055.0  13132.9
              22     2305.1   576.275000   368.008799  1983.1  11039.1
              23     2375.2   593.800000   305.046576  1955.4  11219.0

                                solar
                            std   min   max       std
month weekday hour
1     0       0     2341.175057   0.1   0.1       NaN
              1     2447.057233   0.1   0.1       NaN
              2     2679.795125   NaN   NaN       NaN
              3     2733.835641   NaN   NaN       NaN
              4     2840.367746   NaN   NaN       NaN
...                         ...   ...   ...       ...
12    6       19    4212.173928   0.1  12.8  6.205643
              20    4045.097944   0.1  13.0  6.841296
              21    3936.590515   0.1  12.9  6.843975
              22    3263.962954   0.1  12.9  6.784541
              23    3350.485806   0.1   1.7  0.802081

[2016 rows x 9 columns]

In [ ]:
energy["month"].unique()

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# We can handle a multiindex like the one resulting from a groupby with several columns 
# and several operations in the following way:

df = energy.groupby(["month", "weekday"]).agg({
    "coal": ["sum", "mean"],
    "wind": ["sum", "mean"]
})

# mean coal generation on Tuesdays in January
df.loc[(1, 1), ("coal", "mean")]

4230.0858333333335

In [ ]:
energy["datetime"].values[0][:-6]

'2018-12-31 23:00:00'

In [ ]:
import datetime

a = pd.to_datetime(energy["datetime"].values[0][:-6], format="%Y-%m-%d %H:%M:%S")

a.month

12

When we have a DataFrame with several indices, we can use `unstack()` and `stack()`:

### `stack` and `unstack`

These methods allow us to "move" labels from rows to columns and viceversa
* `unstack` moves row labels to column labels
* `stack` moves column labels to row labels

By default, the level at which these function operates is on the -1th level.

In [ ]:
# create DF with 2 indices
df = energy.groupby(["month", "weekday"]).agg({
    "coal": ["sum", "mean"],
    "wind": ["sum", "mean"]
})

# sum of wind on thrusdays in august
df.loc[(8, 3), ("wind", "sum")]

468409.5

In [ ]:
# move `weekday` from rows to columns: unstack weekday
df = energy.groupby(["month", "weekday"]).agg({
    "coal": ["sum", "mean"],
    "wind": ["sum", "mean"]
}).unstack(level="weekday")

# avg coal on saturdays in november
df.loc[11, ("coal", "mean", 5)]

576.5266666666666

In [ ]:
# move ("coal", "wind") from columns labels to rows: stack 0
df = energy.groupby(["month", "weekday"]).agg({
    "coal": ["sum", "mean"],
    "wind": ["sum", "mean"]
}).stack(1)

# whats the sum of wind on wednesdays in july
df.loc[(7, 2, "sum"), "wind"]

495089.4

## Practice

### Exercise 1: `energy` dataset
What's the maximum solar power generation happened in August?

### Exercise 2: `energy` dataset
What's the average production of each of the following technologies on Hour 5

```Python
tech = ["nuclear", "solar", "hydro"]
```

### Exercise 3:
Create a new column called `stop_wind` with value 1 if `spot_price` is below 20, and 0 otherwise.

### Exercise 4:
Create a new column called weekend with 0 if weekday=0,1,2,3,4 and 1 otherwise