# Session 18: Pandas practice

Dataset: https://www.kaggle.com/datasets/adilshamim8/social-media-addiction-vs-relationships

* **Student_ID:** A unique integer identifier assigned to each survey respondent to enable de-duplication and track individual records without revealing personal information.
* **Age:** The student’s age in completed years at the time of the survey, used to segment analysis by age group and control for developmental differences.
* **Gender:** The student’s self-reported gender, recorded as “Male” or “Female” to allow for demographic breakdowns in usage and outcome measures.
* **Academic_Level:** The highest level of education the respondent is currently enrolled in, with categories: “High School,” “Undergraduate,” or “Graduate,” facilitating stratified analyses by academic stage.
* **Country:** The country of residence where the student completed the survey, enabling cross-country comparisons of social media behaviors and impacts.
* **Avg_Daily_Usage_Hours:** The average number of hours per day the student spends on social media platforms, calculated from self-reported weekday and weekend usage estimates.
* **Most_Used_Platform:** The social media platform on which the student spends the most time (e.g., Instagram, Facebook, TikTok), used to examine platform-specific effects.
* **Affects_Academic_Performance:** A binary indicator (“Yes”/“No”) reflecting whether the student perceives their social media use as having a negative impact on their academic performance.
* **Sleep_Hours_Per_Night:** The respondent’s average nightly sleep duration in hours, provided to investigate correlations between screen time and sleep quality/quantity.
* **Mental_Health_Score:** A self-rated integer from 1 (poor) to 10 (excellent) indicating overall mental well-being, allowing assessment of potential associations with social media habits.
* **Relationship_Status:** The student’s current romantic relationship status, categorized as “Single,” “In Relationship,” or “Complicated,” to explore social media’s impact on interpersonal dynamics.
* **Conflicts_Over_Social_Media:** The number of arguments or disagreements the student reports having had with family, friends, or partners due to their social media use, serving as a proxy for social friction.
* **Addicted_Score:** A composite score from 1 (low addiction) to 10 (high addiction) based on a standardized survey scale (e.g., Bergen Social Media Addiction Scale), quantifying the degree of problematic usage.

## 1. Read the dataset into a DataFrame

In [ ]:
import pandas as pd

students = pd.read_csv(
    "/Users/dgh/Desktop/pda_mbads/pda1/data/social_media_addiction.csv"
)

students.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

## 2. Introductory questions about the dataset

* How many rows and columns does the dataset have?

In [5]:
students.shape

(705, 13)

* What are the names of the columns?

In [10]:
students.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
       'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
       'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
       'Mental_Health_Score', 'Relationship_Status',
       'Conflicts_Over_Social_Media', 'Addicted_Score'],
      dtype='object')

* Convert all the column names to snake case.

In [ ]:
students.columns = [column.lower().replace(" ", "_") for column in students.columns]

students.head()

,student_id,age,gender,academic_level,country,avg_daily_usage_hours,most_used_platform,affects_academic_performance,sleep_hours_per_night,mental_health_score,relationship_status,conflicts_over_social_media,addicted_score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

* Convert all `Yes/No` in the `Affects_Academic_Performance` column to `True/False`.

In [ ]:
students["affects_academic_performance"].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
import numpy as np

students["affects_academic_performance"] = np.where(
    students["affects_academic_performance"] == "Yes", True, False
)

students.head()

,student_id,age,gender,academic_level,country,avg_daily_usage_hours,most_used_platform,affects_academic_performance,sleep_hours_per_night,mental_health_score,relationship_status,conflicts_over_social_media,addicted_score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,True,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,False,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,True,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,False,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,True,6.0,6,In Relationship,2,7

In [18]:
True * 2

2

In [ ]:
def bool_to_int(b):
    return b * 1


students["affects_academic_performance_int"] = students[
    "affects_academic_performance"
].map(bool_to_int)

students.head()

,student_id,age,gender,academic_level,country,avg_daily_usage_hours,most_used_platform,affects_academic_performance,sleep_hours_per_night,mental_health_score,relationship_status,conflicts_over_social_media,addicted_score,affects_academic_performance_int
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,True,6.5,6,In Relationship,3,8,1
1,2,22,Male,Graduate,India,2.1,Twitter,False,7.5,8,Single,0,3,0
2,3,20,Female,Undergraduate,USA,6.0,TikTok,True,5.0,5,Complicated,4,9,1
3,4,18,Male,High School,UK,3.0,YouTube,False,7.0,7,Single,1,4,0
4,5,21,Male,Graduate,Canada,4.5,Facebook,True,6.0,6,In Relationship,2,7,1

In [ ]:
students["affects_academic_performance_int"] = students[
    "affects_academic_performance"
].map(lambda x: x * 1)

students.head()

,student_id,age,gender,academic_level,country,avg_daily_usage_hours,most_used_platform,affects_academic_performance,sleep_hours_per_night,mental_health_score,relationship_status,conflicts_over_social_media,addicted_score,affects_academic_performance_int
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,True,6.5,6,In Relationship,3,8,1
1,2,22,Male,Graduate,India,2.1,Twitter,False,7.5,8,Single,0,3,0
2,3,20,Female,Undergraduate,USA,6.0,TikTok,True,5.0,5,Complicated,4,9,1
3,4,18,Male,High School,UK,3.0,YouTube,False,7.0,7,Single,1,4,0
4,5,21,Male,Graduate,Canada,4.5,Facebook,True,6.0,6,In Relationship,2,7,1

* Convert the `Avg_Daily_Usage_Hours` column to a percentage of the year, spent on social media.

In [ ]:
students["avg_daily_usage_hours_pct_year"] = (
    100 * students["avg_daily_usage_hours"] / 8760
)

students["avg_daily_usage_hours_pct_year"]

0      0.059361
1      0.023973
2      0.068493
3      0.034247
4      0.051370
         ...
700    0.053653
701    0.077626
702    0.063927
703    0.049087
704    0.070776
Name: avg_daily_usage_hours_pct_year, Length: 705, dtype: float64

## 3. About the `Country` column

* How many unique countries are there in the dataset?

In [ ]:
students["country"].nunique()  # count(distinct country)

110

In [ ]:
len(students["country"].unique())  # select distinct country

110

* Which is the most common country?

In [ ]:
students["country"].value_counts().idxmax()

'India'

In [ ]:
students["country"] == students["country"].value_counts().idxmax()

0      False
1       True
2      False
3      False
4      False
       ...
700    False
701    False
702    False
703    False
704    False
Name: country, Length: 705, dtype: bool

In [ ]:
# return all the rows containing the country that's most frequent in the df
students[students["country"] == students["country"].value_counts().idxmax()]

,student_id,age,gender,academic_level,country,avg_daily_usage_hours,most_used_platform,affects_academic_performance,sleep_hours_per_night,mental_health_score,relationship_status,conflicts_over_social_media,addicted_score,affects_academic_performance_int,avg_daily_usage_hours_pct_year
1,2,22,Male,Graduate,India,2.1,Twitter,False,7.5,8,Single,0,3,0,0.023973
111,112,21,Female,Undergraduate,India,5.8,TikTok,True,5.9,6,In Relationship,3,7,1,0.066210
117,118,20,Female,Undergraduate,India,5.7,Instagram,True,6.1,6,Single,3,7,1,0.065068
123,124,22,Female,Graduate,India,5.8,Instagram,True,5.8,6,In Relationship,3,7,1,0.066210
129,130,21,Female,Graduate,India,5.6,Instagram,True,5.6,6,In Relationship,3,7,1,0.063927
135,136,20,Female,Undergraduate,India,5.4,Instagram,True,5.4,6,In Relationship,3,7,1,0.061644
141,142,21,Female,Graduate,India,5.2,Instagram,True,5.2,6,In Relationship,3,7,1,0.059361
147,148,20,Female,Undergraduate,India,5.0,Instagram,True,5.0,6,In Relationship,3,7,1,0.057078
153,154,21,Female,Graduate,India,4.8,Instagram,True,4.8,6,In Relationship,3,7,1,0.054795
159,160,20,Female,Undergraduate,India,4.6,Instagram,True,4.6,6,In Relationship,3,7,1,0.052511
161,162,21,Male,Graduate,India,4.8,Facebook,False,7.2,7,In Relationship,2,6,0,0.054795
167,168,22,Male,Graduate,India,5.2,Facebook,False,7.1,7,In Relationship,2,6,0,0.059361
173,174,21,Male,Graduate,India,5.1,Facebook,False,7.4,7,In Relationship,2,6,0,0.058219
179,180,22,Male,Graduate,India,5.0,Facebook,False,7.6,7,In Relationship,2,6,0,0.057078
185,186,21,Male,Graduate,India,4.9,Facebook,False,7.8,7,In Relationship,2,6,0,0.055936
191,192,22,Male,Graduate,India,4.8,Facebook,False,8.0,7,In Relationship,2,6,0,0.054795
197,198,21,Male,Graduate,India,4.7,Facebook,False,8.2,7,In Relationship,2,6,0,0.053653
203,204,22,Male,Graduate,India,4.6,Facebook,False,8.4,7,In Relationship,2,6,0,0.052511
209,210,21,Male,Graduate,India,4.5,Facebook,False,8.6,7,In Relationship,2,6,0,0.051370
215,216,22,Male,Graduate,India,4.4,Facebook,False,8.8,7,In Relationship,2,6,0,0.050228
323,324,22,Male,Graduate,India,5.8,WhatsApp,True,6.5,5,In Relationship,4,8,1,0.066210
333,334,21,Male,Graduate,India,5.9,WhatsApp,True,6.4,5,In Relationship,4,8,1,0.067352
343,344,22,Male,Graduate,India,6.0,WhatsApp,True,6.3,5,In Relationship,4,8,1,0.068493
353,354,21,Male,Graduate,India,6.1,WhatsApp,True,6.2,5,In Relationship,4,8,1,0.069635
363,364,22,Male,Graduate,India,6.2,WhatsApp,True,6.1,5,In Relationship,4,8,1,0.070776
373,374,21,Male,Graduate,India,6.3,WhatsApp,True,6.0,5,In Relationship,4,8,1,0.071918
383,384,22,Male,Graduate,India,6.4,WhatsApp,True,5.9,5,In Relationship,4,8,1,0.073059
393,394,21,Male,Graduate,India,6.5,WhatsApp,True,5.8,5,In Relationship,4,8,1,0.074201
403,404,22,Male,Graduate,India,6.6,WhatsApp,True,5.7,5,In Relationship,4,8,1,0.075342
413,414,21,Male,Graduate,India,6.7,WhatsApp,True,5.6,5,In Relationship,4,8,1,0.076484
423,424,22,Male,Graduate,India,6.8,WhatsApp,True,5.5,5,In Relationship,4,8,1,0.077626
433,434,21,Male,Graduate,India,6.9,WhatsApp,True,5.4,5,In Relationship,4,8,1,0.078767
443,444,22,Male,Graduate,India,7.0,WhatsApp,True,5.3,5,In Relationship,4,8,1,0.079909
453,454,21,Male,Graduate,India,7.1,WhatsApp,True,5.2,5,In Relationship,4,8,1,0.081050
463,464,22,Male,Graduate,India,7.2,WhatsApp,True,5.1,5,In Relationship,4,8,1,0.082192
473,474,21,Male,Graduate,India,7.3,WhatsApp,True,5.0,5,In Relationship,4,8,1,0.083333
483,484,22,Male,Graduate,India,7.4,WhatsApp,True,4.9,5,In Relationship,4,8,1,0.084475
493,494,21,Male,Graduate,India,7.5,WhatsApp,True,4.8,5,In Relationship,4,8,1,0.085616
508,509,19,Female,Undergraduate,India,6.8,WhatsApp,True,6.0,5,In Relationship,4,8,1,0.077626
518,519,20,Female,Undergraduate,India,6.9,WhatsApp,True,5.9,5,In Relationship,4,8,1,0.078767
528,529,19,Female,Undergraduate,India,7.0,WhatsApp,True,5.8,5,In Relationship,4,8,1,0.079909
538,539,20,Female,Undergraduate,India,7.1,WhatsApp,True,5.7,5,In Relationship,4,8,1,0.081050
548,549,19,Female,Undergraduate,India,7.2,WhatsApp,True,5.6,5,In Relationship,4,8,1,0.082192
558,559,20,Female,Undergraduate,India,7.3,WhatsApp,True,5.5,5,In Relationship,4,8,1,0.083333
568,569,19,Female,Undergraduate,India,7.4,WhatsApp,True,5.4,5,In Relationship,4,8,1,0.084475
573,574,22,Male,Graduate,India,7.2,Facebook,True,5.9,4,Single,5,9,1,0.082192
590,591,19,Female,Undergraduate,India,7.0,Instagram,True,5.8,4,Single,5,9,1,0.079909
607,608,21,Male,Undergraduate,India,7.1,Facebook,True,5.7,4,Single,5,9,1,0.081050
624,625,24,Female,Graduate,India,7.0,TikTok,True,5.8,4,Single,5,9,1,0.079909
641,642,19,Male,Undergraduate,India,7.2,TikTok,True,5.7,4,Single,5,9,1,0.082192
658,659,20,Female,Undergraduate,India,7.1,TikTok,True,5.8,4,Single,5,9,1,0.081050
675,676,22,Male,Graduate,India,7.2,Facebook,True,5.7,4,Single,5,9,1,0.082192
692,693,19,Female,Undergraduate,India,7.0,TikTok,True,5.8,4,Single,5,9,1,0.079909

* Which country has the highest average daily usage hours?

In [ ]:
students["country"][students["avg_daily_usage_hours"].idxmax()]

'USA'

In [ ]:
students.groupby("country")[["avg_daily_usage_hours"]].mean().idxmax()

avg_daily_usage_hours    USA
dtype: object

In [ ]:
(
    students.groupby("country")[["avg_daily_usage_hours"]]
    .mean()
    .sort_values(by="avg_daily_usage_hours", ascending=False)
    .index[0]
)

'USA'

## 4. About the Social Media column

* How many unique social media platforms are there in the dataset?

In [ ]:
students["most_used_platform"].unique().size

12

In [ ]:
students["most_used_platform"].nunique()

12

In [ ]:
len(students["most_used_platform"].unique())

12

* Which social media platform is the most popular?

In [ ]:
students["most_used_platform"].value_counts().idxmax()

'Instagram'

In [ ]:
students["most_used_platform"].value_counts().idxmin()

'YouTube'

* Which social media platform has the highest average daily usage hours?

In [ ]:
(students.groupby("most_used_platform")["avg_daily_usage_hours"].mean().idxmax())

'WhatsApp'

* Which social media platform has the highest percentage of users affected in their academic performance?

In [ ]:
max_pct_affected = (
    students.groupby("most_used_platform")["affects_academic_performance"].mean().max()
)

mask = (
    students.groupby("most_used_platform")["affects_academic_performance"].mean()
    == max_pct_affected
)

pct_per_platform = students.groupby("most_used_platform")[
    "affects_academic_performance"
].mean()

list(pct_per_platform[mask].index)

['KakaoTalk', 'WhatsApp']

* Which social media is the preferred platform for each relationship status?

In [ ]:
(
    students.groupby("relationship_status")["most_used_platform"]
    # .agg(lambda x: x.value_counts().idxmax())
    # .agg(lambda x: x.mode())
)

AttributeError: 'SeriesGroupBy' object has no attribute 'mode'

* Which social media is the preferred platform for each age group? 3 groups. If there are no groups, create 3 groups.

In [ ]:
# g1 18-19, g2 20-22, g3 23-24


def age_group(age):
    if age < 20:
        group = "g1"
    elif age < 23:
        group = "g2"
    else:
        group = "g3"
    return group


students["age_group"] = students["age"].map(age_group)

students[["age", "age_group"]]

     age age_group
0     19        g1
1     22        g2
2     20        g2
3     18        g1
4     21        g2
..   ...       ...
700   20        g2
701   23        g3
702   21        g2
703   24        g3
704   19        g1

[705 rows x 2 columns]

* Which social media is the one with the lowest average Mental Health Score?

## 5. Correlations

* What is the correlation between `Avg_Daily_Usage_Hours` and `Sleep_Hours_Per_Night`?

* What is the correlation between `Avg_Daily_Usage_Hours` and `Mental_Health_Score`?

* What is the correlation between `Avg_Daily_Usage_Hours` and `Addicted_Score`?

## 6. Conflicts and usage

* What is the average number of conflicts over social media per country?

* Which country has the highest average number of conflicts over social media?

* Which platform has the highest average number of conflicts over social media?

* Is the number of conflicts over social media correlated with the average daily usage hours?

* Is the number of conflicts over social media correlated with the mental health?

## 7. Academic performance and usage

* What is the average daily usage hours for students who say social media affects their academic performance?

* What is the average daily usage hours for students who say social media does not affect their academic performance?

* What is the average mental health score for students who say social media affects their academic performance?

* What is the average mental health score for students who say social media does not affect their academic performance?

* Which academic level has the highest average daily usage hours?

## 8. Gender analysis

* What is the average daily usage hours per gender?

* Is there a difference between the preferred social media platform for each gender?

* Do gender behave the same across the different academic levels in terms of average daily usage hours?

* Which gender is more likely to say that social media affects their academic performance?

* Which gender is more likely to report conflicts over social media?

* Which gender has a higher average mental health score?