# Session 05: Practice

## String Operations with Pandas

We will use the pandas library with the `str` accessor to perform string operations on Series objects. This allows us to manipulate and analyze text data efficiently.

Also, we will explore regular expressions (regex) to match patterns in strings, which is a powerful tool for text processing.

For the data, we will use the Kanye Rest API, which provides a collection of Kanye West's quotes. We will extract and manipulate these quotes to demonstrate string operations.

In [27]:
import requests

response = requests.get("https://api.kanye.rest")

response.json()

{'quote': 'There are people sleeping in parking lots'}

In [28]:
import requests
import pandas as pd
from time import sleep

iters = range(10)
quotes = []

for i in iters:
    # get a quote from Kanye's API
    response = requests.get("https://api.kanye.rest")
    response_json = response.json()

    # add the timestamp to the response
    response_json["timestamp"] = pd.Timestamp.now()

    # append the response to the list of quotes
    quotes.append(response_json)
    print(f"Quote {i+1}: {response_json['quote']} at {response_json['timestamp']}")

    # wait for 5 seconds
    sleep(5)

quotes_df = pd.DataFrame(quotes)

Quote 1: I spoke to Dave Chapelle for two hours this morning. He is our modern day Socrates at 2026-01-27 18:49:25.534593
Quote 2: We as a people will heal. We will insure the well being of each other at 2026-01-27 18:49:30.606753
Quote 3: 2024 at 2026-01-27 18:49:35.679028
Quote 4: There's so many lonely emojis man at 2026-01-27 18:49:40.728923
Quote 5: George Bush doesn't care about black people at 2026-01-27 18:49:45.800520
Quote 6: I wish I had a friend like me at 2026-01-27 18:49:50.868014
Quote 7: Truth is my goal. Controversy is my gym. I'll do a hundred reps of controversy for a 6 pack of truth at 2026-01-27 18:49:55.986156
Quote 8: We must and will cure homelessness and hunger. We have the capability as a species at 2026-01-27 18:50:01.061949
Quote 9: My greatest pain in life is that I will never be able to see myself perform live. at 2026-01-27 18:50:06.129631
Quote 10: Only free thinkers at 2026-01-27 18:50:11.208269

In [29]:
quotes_df

,quote,timestamp
0,I spoke to Dave Chapelle for two hours this mo...,2026-01-27 18:49:25.534593
1,We as a people will heal. We will insure the w...,2026-01-27 18:49:30.606753
2,2024,2026-01-27 18:49:35.679028
3,There's so many lonely emojis man,2026-01-27 18:49:40.728923
4,George Bush doesn't care about black people,2026-01-27 18:49:45.800520
5,I wish I had a friend like me,2026-01-27 18:49:50.868014
6,Truth is my goal. Controversy is my gym. I'll ...,2026-01-27 18:49:55.986156
7,We must and will cure homelessness and hunger....,2026-01-27 18:50:01.061949
8,My greatest pain in life is that I will never ...,2026-01-27 18:50:06.129631
9,Only free thinkers,2026-01-27 18:50:11.208269

## Question 2: Text Case Operations

Convert all quotes to uppercase, lowercase, and title case, save the results in new columns.

In [30]:
quotes_df["quote_lower"] = quotes_df["quote"].str.lower()
quotes_df["quote_upper"] = quotes_df["quote"].str.upper()
quotes_df["quote_title"] = quotes_df["quote"].str.title()

## Question 3: Word Count Analysis (1)

Count the number of words in each quote and identify the quote with the most words, using string methods.

In [31]:
# Count words in each quote
quotes_df["word_count"] = quotes_df["quote"].str.split().str.len()

# Find quote with most words
max_words_idx = quotes_df["word_count"].idxmax()
max_words_quote = quotes_df.iloc[max_words_idx]
print(max_words_quote)

quotes_df

quote          Truth is my goal. Controversy is my gym. I'll ...
timestamp                             2026-01-27 18:49:55.986156
quote_lower    truth is my goal. controversy is my gym. i'll ...
quote_upper    TRUTH IS MY GOAL. CONTROVERSY IS MY GYM. I'LL ...
quote_title    Truth Is My Goal. Controversy Is My Gym. I'Ll ...
word_count                                                    21
Name: 6, dtype: object

,quote,timestamp,quote_lower,quote_upper,quote_title,word_count
0,I spoke to Dave Chapelle for two hours this mo...,2026-01-27 18:49:25.534593,i spoke to dave chapelle for two hours this mo...,I SPOKE TO DAVE CHAPELLE FOR TWO HOURS THIS MO...,I Spoke To Dave Chapelle For Two Hours This Mo...,16
1,We as a people will heal. We will insure the w...,2026-01-27 18:49:30.606753,we as a people will heal. we will insure the w...,WE AS A PEOPLE WILL HEAL. WE WILL INSURE THE W...,We As A People Will Heal. We Will Insure The W...,15
2,2024,2026-01-27 18:49:35.679028,2024,2024,2024,1
3,There's so many lonely emojis man,2026-01-27 18:49:40.728923,there's so many lonely emojis man,THERE'S SO MANY LONELY EMOJIS MAN,There'S So Many Lonely Emojis Man,6
4,George Bush doesn't care about black people,2026-01-27 18:49:45.800520,george bush doesn't care about black people,GEORGE BUSH DOESN'T CARE ABOUT BLACK PEOPLE,George Bush Doesn'T Care About Black People,7
5,I wish I had a friend like me,2026-01-27 18:49:50.868014,i wish i had a friend like me,I WISH I HAD A FRIEND LIKE ME,I Wish I Had A Friend Like Me,8
6,Truth is my goal. Controversy is my gym. I'll ...,2026-01-27 18:49:55.986156,truth is my goal. controversy is my gym. i'll ...,TRUTH IS MY GOAL. CONTROVERSY IS MY GYM. I'LL ...,Truth Is My Goal. Controversy Is My Gym. I'Ll ...,21
7,We must and will cure homelessness and hunger....,2026-01-27 18:50:01.061949,we must and will cure homelessness and hunger....,WE MUST AND WILL CURE HOMELESSNESS AND HUNGER....,We Must And Will Cure Homelessness And Hunger....,15
8,My greatest pain in life is that I will never ...,2026-01-27 18:50:06.129631,my greatest pain in life is that i will never ...,MY GREATEST PAIN IN LIFE IS THAT I WILL NEVER ...,My Greatest Pain In Life Is That I Will Never ...,17
9,Only free thinkers,2026-01-27 18:50:11.208269,only free thinkers,ONLY FREE THINKERS,Only Free Thinkers,3

## Question 4: Word Count Analysis (2)

Count the number of words in each quote and identify the quote with the most words, using regex.

In [50]:
import re

words = "qsadfqd qsdefqwefq, qwefqwefq qwefq"

word_count_pattern = r"\b\w+\b"

regex = re.compile(word_count_pattern)

regex.findall(words)

['qsadfqd', 'qsdefqwefq', 'qwefqwefq', 'qwefq']

In [51]:
word_count_pattern = r"\b\w+\b"

# breakdown of pattern
# \b - word boundary: matches the position between a word character and a non-word character, like spaces or punctuation
# \w - word character (alphanumeric characters and underscores)
# + - one or more occurrences
# \b - word boundary

quotes_df["word_count_regex"] = quotes_df["quote"].str.count(word_count_pattern)


quotes_df

,quote,timestamp,quote_lower,quote_upper,quote_title,word_count,word_count_regex,music_flag,quote_music_replaced,capital_words,...,num_sentences,unique_words,lexical_diversity,timestamp_str,year,month,day,hour,minute,second
0,I spoke to Dave Chapelle for two hours this mo...,2026-01-27 18:49:25.534593,i spoke to dave chapelle for two hours this mo...,I SPOKE TO DAVE CHAPELLE FOR TWO HOURS THIS MO...,I Spoke To Dave Chapelle For Two Hours This Mo...,16,16,False,I spoke to Dave Chapelle for two hours this mo...,"[Dave, Chapelle, Socrates]",...,2,16,1.000000,2026-01-27 18:49:25.534593,2026,01,27,18,49,25
1,We as a people will heal. We will insure the w...,2026-01-27 18:49:30.606753,we as a people will heal. we will insure the w...,WE AS A PEOPLE WILL HEAL. WE WILL INSURE THE W...,We As A People Will Heal. We Will Insure The W...,15,15,True,We as a people art heal. We art insure the wel...,[],...,2,13,0.866667,2026-01-27 18:49:30.606753,2026,01,27,18,49,30
2,2024,2026-01-27 18:49:35.679028,2024,2024,2024,1,1,False,2024,[],...,1,1,1.000000,2026-01-27 18:49:35.679028,2026,01,27,18,49,35
3,There's so many lonely emojis man,2026-01-27 18:49:40.728923,there's so many lonely emojis man,THERE'S SO MANY LONELY EMOJIS MAN,There'S So Many Lonely Emojis Man,6,7,False,There's so many lonely emojis man,[There],...,1,6,1.000000,2026-01-27 18:49:40.728923,2026,01,27,18,49,40
4,George Bush doesn't care about black people,2026-01-27 18:49:45.800520,george bush doesn't care about black people,GEORGE BUSH DOESN'T CARE ABOUT BLACK PEOPLE,George Bush Doesn'T Care About Black People,7,8,False,George Bush doesn't care about black people,"[George, Bush]",...,1,7,1.000000,2026-01-27 18:49:45.800520,2026,01,27,18,49,45
5,I wish I had a friend like me,2026-01-27 18:49:50.868014,i wish i had a friend like me,I WISH I HAD A FRIEND LIKE ME,I Wish I Had A Friend Like Me,8,8,False,I wish I had a friend like me,[],...,1,7,0.875000,2026-01-27 18:49:50.868014,2026,01,27,18,49,50
6,Truth is my goal. Controversy is my gym. I'll ...,2026-01-27 18:49:55.986156,truth is my goal. controversy is my gym. i'll ...,TRUTH IS MY GOAL. CONTROVERSY IS MY GYM. I'LL ...,Truth Is My Goal. Controversy Is My Gym. I'Ll ...,21,22,False,Truth is my goal. Controversy is my gym. I'll ...,"[Truth, Controversy]",...,3,17,0.809524,2026-01-27 18:49:55.986156,2026,01,27,18,49,55
7,We must and will cure homelessness and hunger....,2026-01-27 18:50:01.061949,we must and will cure homelessness and hunger....,WE MUST AND WILL CURE HOMELESSNESS AND HUNGER....,We Must And Will Cure Homelessness And Hunger....,15,15,True,We must and art cure homelessness and hunger. ...,[],...,2,13,0.866667,2026-01-27 18:50:01.061949,2026,01,27,18,50,01
8,My greatest pain in life is that I will never ...,2026-01-27 18:50:06.129631,my greatest pain in life is that i will never ...,MY GREATEST PAIN IN LIFE IS THAT I WILL NEVER ...,My Greatest Pain In Life Is That I Will Never ...,17,17,True,My greatest pain in life is that I art never b...,[],...,2,17,1.000000,2026-01-27 18:50:06.129631,2026,01,27,18,50,06
9,Only free thinkers,2026-01-27 18:50:11.208269,only free thinkers,ONLY FREE THINKERS,Only Free Thinkers,3,3,False,Only free thinkers,[Only],...,1,3,1.000000,2026-01-27 18:50:11.208269,2026,01,27,18,50,11

In [34]:
my_string = quotes_df.iloc[6].loc["quote"]

# count wiht split
split_words = my_string.split()
count_split = len(my_string.split())
print(split_words)
print(count_split)

# count regex
regex = re.compile(word_count_pattern)
regex_words = regex.findall(my_string)
count_regex = len(regex.findall(my_string))
print(regex_words)
print(count_regex)

['Truth', 'is', 'my', 'goal.', 'Controversy', 'is', 'my', 'gym.', "I'll", 'do', 'a', 'hundred', 'reps', 'of', 'controversy', 'for', 'a', '6', 'pack', 'of', 'truth']
21
['Truth', 'is', 'my', 'goal', 'Controversy', 'is', 'my', 'gym', 'I', 'll', 'do', 'a', 'hundred', 'reps', 'of', 'controversy', 'for', 'a', '6', 'pack', 'of', 'truth']
22

## Question 5: Find the differences between the two methods used in Questions 3 and 4.

In [35]:
my_string = quotes_df.iloc[6].loc["quote"]

# count wiht split
split_words = my_string.split()
count_split = len(my_string.split())
print(split_words)
print(count_split)

# count regex
regex = re.compile(word_count_pattern)
regex_words = regex.findall(my_string)
count_regex = len(regex.findall(my_string))
print(regex_words)
print(count_regex)

['Truth', 'is', 'my', 'goal.', 'Controversy', 'is', 'my', 'gym.', "I'll", 'do', 'a', 'hundred', 'reps', 'of', 'controversy', 'for', 'a', '6', 'pack', 'of', 'truth']
21
['Truth', 'is', 'my', 'goal', 'Controversy', 'is', 'my', 'gym', 'I', 'll', 'do', 'a', 'hundred', 'reps', 'of', 'controversy', 'for', 'a', '6', 'pack', 'of', 'truth']
22

## Question 6: Text Search and Filtering

Find all quotes that contain the word "I" and count how many times "I" appears in total across all quotes.

In [52]:
# Find quotes containing "I"
quotes_with_i = quotes_df[
    quotes_df["quote"].str.contains(r"\bI\b", regex=True, case=True)
]

quotes_with_i

,quote,timestamp,quote_lower,quote_upper,quote_title,word_count,word_count_regex,music_flag,quote_music_replaced,capital_words,...,num_sentences,unique_words,lexical_diversity,timestamp_str,year,month,day,hour,minute,second
0,I spoke to Dave Chapelle for two hours this mo...,2026-01-27 18:49:25.534593,i spoke to dave chapelle for two hours this mo...,I SPOKE TO DAVE CHAPELLE FOR TWO HOURS THIS MO...,I Spoke To Dave Chapelle For Two Hours This Mo...,16,16,False,I spoke to Dave Chapelle for two hours this mo...,"[Dave, Chapelle, Socrates]",...,2,16,1.000000,2026-01-27 18:49:25.534593,2026,01,27,18,49,25
5,I wish I had a friend like me,2026-01-27 18:49:50.868014,i wish i had a friend like me,I WISH I HAD A FRIEND LIKE ME,I Wish I Had A Friend Like Me,8,8,False,I wish I had a friend like me,[],...,1,7,0.875000,2026-01-27 18:49:50.868014,2026,01,27,18,49,50
6,Truth is my goal. Controversy is my gym. I'll ...,2026-01-27 18:49:55.986156,truth is my goal. controversy is my gym. i'll ...,TRUTH IS MY GOAL. CONTROVERSY IS MY GYM. I'LL ...,Truth Is My Goal. Controversy Is My Gym. I'Ll ...,21,22,False,Truth is my goal. Controversy is my gym. I'll ...,"[Truth, Controversy]",...,3,17,0.809524,2026-01-27 18:49:55.986156,2026,01,27,18,49,55
8,My greatest pain in life is that I will never ...,2026-01-27 18:50:06.129631,my greatest pain in life is that i will never ...,MY GREATEST PAIN IN LIFE IS THAT I WILL NEVER ...,My Greatest Pain In Life Is That I Will Never ...,17,17,True,My greatest pain in life is that I art never b...,[],...,2,17,1.000000,2026-01-27 18:50:06.129631,2026,01,27,18,50,06

## Question 7: Flag Quotes with Specific Words

Flag quotes that contain the word "music" and replace it with "art", taking into account case sensitivity and whitespace.

In [54]:
quotes_df["music_flag"] = quotes_df["quote"].str.contains(r"\b[Tt]ruth\b", regex=True)

quotes_df

,quote,timestamp,quote_lower,quote_upper,quote_title,word_count,word_count_regex,music_flag,quote_music_replaced,capital_words,...,num_sentences,unique_words,lexical_diversity,timestamp_str,year,month,day,hour,minute,second
0,I spoke to Dave Chapelle for two hours this mo...,2026-01-27 18:49:25.534593,i spoke to dave chapelle for two hours this mo...,I SPOKE TO DAVE CHAPELLE FOR TWO HOURS THIS MO...,I Spoke To Dave Chapelle For Two Hours This Mo...,16,16,False,I spoke to Dave Chapelle for two hours this mo...,"[Dave, Chapelle, Socrates]",...,2,16,1.000000,2026-01-27 18:49:25.534593,2026,01,27,18,49,25
1,We as a people will heal. We will insure the w...,2026-01-27 18:49:30.606753,we as a people will heal. we will insure the w...,WE AS A PEOPLE WILL HEAL. WE WILL INSURE THE W...,We As A People Will Heal. We Will Insure The W...,15,15,False,We as a people art heal. We art insure the wel...,[],...,2,13,0.866667,2026-01-27 18:49:30.606753,2026,01,27,18,49,30
2,2024,2026-01-27 18:49:35.679028,2024,2024,2024,1,1,False,2024,[],...,1,1,1.000000,2026-01-27 18:49:35.679028,2026,01,27,18,49,35
3,There's so many lonely emojis man,2026-01-27 18:49:40.728923,there's so many lonely emojis man,THERE'S SO MANY LONELY EMOJIS MAN,There'S So Many Lonely Emojis Man,6,7,False,There's so many lonely emojis man,[There],...,1,6,1.000000,2026-01-27 18:49:40.728923,2026,01,27,18,49,40
4,George Bush doesn't care about black people,2026-01-27 18:49:45.800520,george bush doesn't care about black people,GEORGE BUSH DOESN'T CARE ABOUT BLACK PEOPLE,George Bush Doesn'T Care About Black People,7,8,False,George Bush doesn't care about black people,"[George, Bush]",...,1,7,1.000000,2026-01-27 18:49:45.800520,2026,01,27,18,49,45
5,I wish I had a friend like me,2026-01-27 18:49:50.868014,i wish i had a friend like me,I WISH I HAD A FRIEND LIKE ME,I Wish I Had A Friend Like Me,8,8,False,I wish I had a friend like me,[],...,1,7,0.875000,2026-01-27 18:49:50.868014,2026,01,27,18,49,50
6,Truth is my goal. Controversy is my gym. I'll ...,2026-01-27 18:49:55.986156,truth is my goal. controversy is my gym. i'll ...,TRUTH IS MY GOAL. CONTROVERSY IS MY GYM. I'LL ...,Truth Is My Goal. Controversy Is My Gym. I'Ll ...,21,22,True,Truth is my goal. Controversy is my gym. I'll ...,"[Truth, Controversy]",...,3,17,0.809524,2026-01-27 18:49:55.986156,2026,01,27,18,49,55
7,We must and will cure homelessness and hunger....,2026-01-27 18:50:01.061949,we must and will cure homelessness and hunger....,WE MUST AND WILL CURE HOMELESSNESS AND HUNGER....,We Must And Will Cure Homelessness And Hunger....,15,15,False,We must and art cure homelessness and hunger. ...,[],...,2,13,0.866667,2026-01-27 18:50:01.061949,2026,01,27,18,50,01
8,My greatest pain in life is that I will never ...,2026-01-27 18:50:06.129631,my greatest pain in life is that i will never ...,MY GREATEST PAIN IN LIFE IS THAT I WILL NEVER ...,My Greatest Pain In Life Is That I Will Never ...,17,17,False,My greatest pain in life is that I art never b...,[],...,2,17,1.000000,2026-01-27 18:50:06.129631,2026,01,27,18,50,06
9,Only free thinkers,2026-01-27 18:50:11.208269,only free thinkers,ONLY FREE THINKERS,Only Free Thinkers,3,3,False,Only free thinkers,[Only],...,1,3,1.000000,2026-01-27 18:50:11.208269,2026,01,27,18,50,11

In [57]:
quotes_df["quote"].str.replace(r"[Dd]ave", "dani")

0    I spoke to Dave Chapelle for two hours this mo...
1    We as a people will heal. We will insure the w...
2                                                 2024
3                    There's so many lonely emojis man
4          George Bush doesn't care about black people
5                        I wish I had a friend like me
6    Truth is my goal. Controversy is my gym. I'll ...
7    We must and will cure homelessness and hunger....
8    My greatest pain in life is that I will never ...
9                                   Only free thinkers
Name: quote, dtype: object

In [ ]:
quotes_df["quote_music_replaced"] = (
    quotes_df["quote"].str.replace("Dave", "dani").str.strip()
)

quotes_df

,quote,timestamp,quote_lower,quote_upper,quote_title,word_count,word_count_regex,music_flag,quote_music_replaced
0,I spoke to Dave Chapelle for two hours this mo...,2026-01-27 18:49:25.534593,i spoke to dave chapelle for two hours this mo...,I SPOKE TO DAVE CHAPELLE FOR TWO HOURS THIS MO...,I Spoke To Dave Chapelle For Two Hours This Mo...,16,16,False,I spoke to Dave Chapelle for two hours this mo...
1,We as a people will heal. We will insure the w...,2026-01-27 18:49:30.606753,we as a people will heal. we will insure the w...,WE AS A PEOPLE WILL HEAL. WE WILL INSURE THE W...,We As A People Will Heal. We Will Insure The W...,15,15,True,We as a people art heal. We art insure the wel...
2,2024,2026-01-27 18:49:35.679028,2024,2024,2024,1,1,False,2024
3,There's so many lonely emojis man,2026-01-27 18:49:40.728923,there's so many lonely emojis man,THERE'S SO MANY LONELY EMOJIS MAN,There'S So Many Lonely Emojis Man,6,7,False,There's so many lonely emojis man
4,George Bush doesn't care about black people,2026-01-27 18:49:45.800520,george bush doesn't care about black people,GEORGE BUSH DOESN'T CARE ABOUT BLACK PEOPLE,George Bush Doesn'T Care About Black People,7,8,False,George Bush doesn't care about black people
5,I wish I had a friend like me,2026-01-27 18:49:50.868014,i wish i had a friend like me,I WISH I HAD A FRIEND LIKE ME,I Wish I Had A Friend Like Me,8,8,False,I wish I had a friend like me
6,Truth is my goal. Controversy is my gym. I'll ...,2026-01-27 18:49:55.986156,truth is my goal. controversy is my gym. i'll ...,TRUTH IS MY GOAL. CONTROVERSY IS MY GYM. I'LL ...,Truth Is My Goal. Controversy Is My Gym. I'Ll ...,21,22,False,Truth is my goal. Controversy is my gym. I'll ...
7,We must and will cure homelessness and hunger....,2026-01-27 18:50:01.061949,we must and will cure homelessness and hunger....,WE MUST AND WILL CURE HOMELESSNESS AND HUNGER....,We Must And Will Cure Homelessness And Hunger....,15,15,True,We must and art cure homelessness and hunger. ...
8,My greatest pain in life is that I will never ...,2026-01-27 18:50:06.129631,my greatest pain in life is that i will never ...,MY GREATEST PAIN IN LIFE IS THAT I WILL NEVER ...,My Greatest Pain In Life Is That I Will Never ...,17,17,True,My greatest pain in life is that I art never b...
9,Only free thinkers,2026-01-27 18:50:11.208269,only free thinkers,ONLY FREE THINKERS,Only Free Thinkers,3,3,False,Only free thinkers

## Question 8: Regular Expressions - Finding Patterns

Use regular expressions to extract all the words that start with a capital letter followed by at least 3 lowercase letters from the quotes.

Extract them as a list of words.

In [39]:
# Find quotes containing words that start with capital letter + 3+ lowercase letters
import re

# Pattern: Capital letter followed by 3 or more lowercase letters
pattern = r"\b[A-Z][a-z]{3,}\b"

# Find all matches in each quote
quotes_df["capital_words"] = quotes_df["quote"].str.findall(pattern)

quotes_df

,quote,timestamp,quote_lower,quote_upper,quote_title,word_count,word_count_regex,music_flag,quote_music_replaced,capital_words
0,I spoke to Dave Chapelle for two hours this mo...,2026-01-27 18:49:25.534593,i spoke to dave chapelle for two hours this mo...,I SPOKE TO DAVE CHAPELLE FOR TWO HOURS THIS MO...,I Spoke To Dave Chapelle For Two Hours This Mo...,16,16,False,I spoke to Dave Chapelle for two hours this mo...,"[Dave, Chapelle, Socrates]"
1,We as a people will heal. We will insure the w...,2026-01-27 18:49:30.606753,we as a people will heal. we will insure the w...,WE AS A PEOPLE WILL HEAL. WE WILL INSURE THE W...,We As A People Will Heal. We Will Insure The W...,15,15,True,We as a people art heal. We art insure the wel...,[]
2,2024,2026-01-27 18:49:35.679028,2024,2024,2024,1,1,False,2024,[]
3,There's so many lonely emojis man,2026-01-27 18:49:40.728923,there's so many lonely emojis man,THERE'S SO MANY LONELY EMOJIS MAN,There'S So Many Lonely Emojis Man,6,7,False,There's so many lonely emojis man,[There]
4,George Bush doesn't care about black people,2026-01-27 18:49:45.800520,george bush doesn't care about black people,GEORGE BUSH DOESN'T CARE ABOUT BLACK PEOPLE,George Bush Doesn'T Care About Black People,7,8,False,George Bush doesn't care about black people,"[George, Bush]"
5,I wish I had a friend like me,2026-01-27 18:49:50.868014,i wish i had a friend like me,I WISH I HAD A FRIEND LIKE ME,I Wish I Had A Friend Like Me,8,8,False,I wish I had a friend like me,[]
6,Truth is my goal. Controversy is my gym. I'll ...,2026-01-27 18:49:55.986156,truth is my goal. controversy is my gym. i'll ...,TRUTH IS MY GOAL. CONTROVERSY IS MY GYM. I'LL ...,Truth Is My Goal. Controversy Is My Gym. I'Ll ...,21,22,False,Truth is my goal. Controversy is my gym. I'll ...,"[Truth, Controversy]"
7,We must and will cure homelessness and hunger....,2026-01-27 18:50:01.061949,we must and will cure homelessness and hunger....,WE MUST AND WILL CURE HOMELESSNESS AND HUNGER....,We Must And Will Cure Homelessness And Hunger....,15,15,True,We must and art cure homelessness and hunger. ...,[]
8,My greatest pain in life is that I will never ...,2026-01-27 18:50:06.129631,my greatest pain in life is that i will never ...,MY GREATEST PAIN IN LIFE IS THAT I WILL NEVER ...,My Greatest Pain In Life Is That I Will Never ...,17,17,True,My greatest pain in life is that I art never b...,[]
9,Only free thinkers,2026-01-27 18:50:11.208269,only free thinkers,ONLY FREE THINKERS,Only Free Thinkers,3,3,False,Only free thinkers,[Only]

## Question 9: String Splitting and Extraction

Split each quote into individual words and extract the first and last word of each quote. Create new columns for these values.

In [58]:
# Split quotes into words and extract first and last words
quotes_df["words"] = quotes_df["quote"].str.split()
quotes_df["first_word"] = quotes_df["words"].str[0]
quotes_df["last_word"] = quotes_df["words"].str[-1]

# Extract first and last words as lists
quotes_df[["words", "first_word", "last_word"]]

                                               words first_word last_word
0  [I, spoke, to, Dave, Chapelle, for, two, hours...          I  Socrates
1  [We, as, a, people, will, heal., We, will, ins...         We     other
2                                             [2024]       2024      2024
3           [There's, so, many, lonely, emojis, man]    There's       man
4  [George, Bush, doesn't, care, about, black, pe...     George    people
5             [I, wish, I, had, a, friend, like, me]          I        me
6  [Truth, is, my, goal., Controversy, is, my, gy...      Truth     truth
7  [We, must, and, will, cure, homelessness, and,...         We   species
8  [My, greatest, pain, in, life, is, that, I, wi...         My     live.
9                             [Only, free, thinkers]       Only  thinkers

In [41]:
# homework what if there is only one word??

In [ ]:
# split into words and extract first and last words with regex
# homework for checking in regex101

quotes_df["first_word"] = quotes_df["quote"].str.extract(r"(\b\w+\b)", expand=False)
quotes_df["last_word"] = quotes_df["quote"].str.extract(
    r"(\b\w+\b)(?!.*\b\w+\b)", expand=False
)

quotes_df[["quote", "first_word", "last_word"]]

                                               quote first_word last_word
0  I spoke to Dave Chapelle for two hours this mo...          I  Socrates
1  We as a people will heal. We will insure the w...         We     other
2                                               2024       2024      2024
3                  There's so many lonely emojis man      There       man
4        George Bush doesn't care about black people     George    people
5                      I wish I had a friend like me          I        me
6  Truth is my goal. Controversy is my gym. I'll ...      Truth     truth
7  We must and will cure homelessness and hunger....         We   species
8  My greatest pain in life is that I will never ...         My      live
9                                 Only free thinkers       Only  thinkers

In [43]:
quotes_df["quote"].str.extract(r"(\b\w+\b)[\W]*$")

          0
0  Socrates
1     other
2      2024
3       man
4    people
5        me
6     truth
7   species
8      live
9  thinkers

## Question 11: Text Statistics and Analysis

Calculate various text statistics for each quote:

* Number of sentences
* Number of unique words
* Ratio of unique words to total words (lexical diversity)

In [59]:
"hello!".split("!")

['hello', '']

In [44]:
# Ana suggests thisshould be homework
# number of sentences

sentences_pattern = r"[\.\!\?]"
# breakdown of pattern
# [.!?] - matches any of the characters ., !, or ?
# + - one or more occurrences

quotes_df["sentences"] = quotes_df["quote"].str.split(sentences_pattern)
quotes_df["num_sentences"] = quotes_df["quote"].str.count(sentences_pattern) + 1
# +1 to count the last sentence that doesn't end with a punctuation mark

quotes_df.loc[3]["sentences"]

["There's so many lonely emojis man"]

In [45]:
# number of unique words and total words

quotes_df["unique_words"] = quotes_df["quote"].str.split().apply(lambda x: len(set(x)))

quotes_df

,quote,timestamp,quote_lower,quote_upper,quote_title,word_count,word_count_regex,music_flag,quote_music_replaced,capital_words,words,first_word,last_word,sentences,num_sentences,unique_words
0,I spoke to Dave Chapelle for two hours this mo...,2026-01-27 18:49:25.534593,i spoke to dave chapelle for two hours this mo...,I SPOKE TO DAVE CHAPELLE FOR TWO HOURS THIS MO...,I Spoke To Dave Chapelle For Two Hours This Mo...,16,16,False,I spoke to Dave Chapelle for two hours this mo...,"[Dave, Chapelle, Socrates]","[I, spoke, to, Dave, Chapelle, for, two, hours...",I,Socrates,[I spoke to Dave Chapelle for two hours this m...,2,16
1,We as a people will heal. We will insure the w...,2026-01-27 18:49:30.606753,we as a people will heal. we will insure the w...,WE AS A PEOPLE WILL HEAL. WE WILL INSURE THE W...,We As A People Will Heal. We Will Insure The W...,15,15,True,We as a people art heal. We art insure the wel...,[],"[We, as, a, people, will, heal., We, will, ins...",We,other,"[We as a people will heal, We will insure the...",2,13
2,2024,2026-01-27 18:49:35.679028,2024,2024,2024,1,1,False,2024,[],[2024],2024,2024,[2024],1,1
3,There's so many lonely emojis man,2026-01-27 18:49:40.728923,there's so many lonely emojis man,THERE'S SO MANY LONELY EMOJIS MAN,There'S So Many Lonely Emojis Man,6,7,False,There's so many lonely emojis man,[There],"[There's, so, many, lonely, emojis, man]",There,man,[There's so many lonely emojis man],1,6
4,George Bush doesn't care about black people,2026-01-27 18:49:45.800520,george bush doesn't care about black people,GEORGE BUSH DOESN'T CARE ABOUT BLACK PEOPLE,George Bush Doesn'T Care About Black People,7,8,False,George Bush doesn't care about black people,"[George, Bush]","[George, Bush, doesn't, care, about, black, pe...",George,people,[George Bush doesn't care about black people],1,7
5,I wish I had a friend like me,2026-01-27 18:49:50.868014,i wish i had a friend like me,I WISH I HAD A FRIEND LIKE ME,I Wish I Had A Friend Like Me,8,8,False,I wish I had a friend like me,[],"[I, wish, I, had, a, friend, like, me]",I,me,[I wish I had a friend like me],1,7
6,Truth is my goal. Controversy is my gym. I'll ...,2026-01-27 18:49:55.986156,truth is my goal. controversy is my gym. i'll ...,TRUTH IS MY GOAL. CONTROVERSY IS MY GYM. I'LL ...,Truth Is My Goal. Controversy Is My Gym. I'Ll ...,21,22,False,Truth is my goal. Controversy is my gym. I'll ...,"[Truth, Controversy]","[Truth, is, my, goal., Controversy, is, my, gy...",Truth,truth,"[Truth is my goal, Controversy is my gym, I'...",3,17
7,We must and will cure homelessness and hunger....,2026-01-27 18:50:01.061949,we must and will cure homelessness and hunger....,WE MUST AND WILL CURE HOMELESSNESS AND HUNGER....,We Must And Will Cure Homelessness And Hunger....,15,15,True,We must and art cure homelessness and hunger. ...,[],"[We, must, and, will, cure, homelessness, and,...",We,species,[We must and will cure homelessness and hunger...,2,13
8,My greatest pain in life is that I will never ...,2026-01-27 18:50:06.129631,my greatest pain in life is that i will never ...,MY GREATEST PAIN IN LIFE IS THAT I WILL NEVER ...,My Greatest Pain In Life Is That I Will Never ...,17,17,True,My greatest pain in life is that I art never b...,[],"[My, greatest, pain, in, life, is, that, I, wi...",My,live,[My greatest pain in life is that I will never...,2,17
9,Only free thinkers,2026-01-27 18:50:11.208269,only free thinkers,ONLY FREE THINKERS,Only Free Thinkers,3,3,False,Only free thinkers,[Only],"[Only, free, thinkers]",Only,thinkers,[Only free thinkers],1,3

In [46]:
# lexical diversity

quotes_df["lexical_diversity"] = quotes_df["unique_words"] / quotes_df["word_count"]

quotes_df

,quote,timestamp,quote_lower,quote_upper,quote_title,word_count,word_count_regex,music_flag,quote_music_replaced,capital_words,words,first_word,last_word,sentences,num_sentences,unique_words,lexical_diversity
0,I spoke to Dave Chapelle for two hours this mo...,2026-01-27 18:49:25.534593,i spoke to dave chapelle for two hours this mo...,I SPOKE TO DAVE CHAPELLE FOR TWO HOURS THIS MO...,I Spoke To Dave Chapelle For Two Hours This Mo...,16,16,False,I spoke to Dave Chapelle for two hours this mo...,"[Dave, Chapelle, Socrates]","[I, spoke, to, Dave, Chapelle, for, two, hours...",I,Socrates,[I spoke to Dave Chapelle for two hours this m...,2,16,1.000000
1,We as a people will heal. We will insure the w...,2026-01-27 18:49:30.606753,we as a people will heal. we will insure the w...,WE AS A PEOPLE WILL HEAL. WE WILL INSURE THE W...,We As A People Will Heal. We Will Insure The W...,15,15,True,We as a people art heal. We art insure the wel...,[],"[We, as, a, people, will, heal., We, will, ins...",We,other,"[We as a people will heal, We will insure the...",2,13,0.866667
2,2024,2026-01-27 18:49:35.679028,2024,2024,2024,1,1,False,2024,[],[2024],2024,2024,[2024],1,1,1.000000
3,There's so many lonely emojis man,2026-01-27 18:49:40.728923,there's so many lonely emojis man,THERE'S SO MANY LONELY EMOJIS MAN,There'S So Many Lonely Emojis Man,6,7,False,There's so many lonely emojis man,[There],"[There's, so, many, lonely, emojis, man]",There,man,[There's so many lonely emojis man],1,6,1.000000
4,George Bush doesn't care about black people,2026-01-27 18:49:45.800520,george bush doesn't care about black people,GEORGE BUSH DOESN'T CARE ABOUT BLACK PEOPLE,George Bush Doesn'T Care About Black People,7,8,False,George Bush doesn't care about black people,"[George, Bush]","[George, Bush, doesn't, care, about, black, pe...",George,people,[George Bush doesn't care about black people],1,7,1.000000
5,I wish I had a friend like me,2026-01-27 18:49:50.868014,i wish i had a friend like me,I WISH I HAD A FRIEND LIKE ME,I Wish I Had A Friend Like Me,8,8,False,I wish I had a friend like me,[],"[I, wish, I, had, a, friend, like, me]",I,me,[I wish I had a friend like me],1,7,0.875000
6,Truth is my goal. Controversy is my gym. I'll ...,2026-01-27 18:49:55.986156,truth is my goal. controversy is my gym. i'll ...,TRUTH IS MY GOAL. CONTROVERSY IS MY GYM. I'LL ...,Truth Is My Goal. Controversy Is My Gym. I'Ll ...,21,22,False,Truth is my goal. Controversy is my gym. I'll ...,"[Truth, Controversy]","[Truth, is, my, goal., Controversy, is, my, gy...",Truth,truth,"[Truth is my goal, Controversy is my gym, I'...",3,17,0.809524
7,We must and will cure homelessness and hunger....,2026-01-27 18:50:01.061949,we must and will cure homelessness and hunger....,WE MUST AND WILL CURE HOMELESSNESS AND HUNGER....,We Must And Will Cure Homelessness And Hunger....,15,15,True,We must and art cure homelessness and hunger. ...,[],"[We, must, and, will, cure, homelessness, and,...",We,species,[We must and will cure homelessness and hunger...,2,13,0.866667
8,My greatest pain in life is that I will never ...,2026-01-27 18:50:06.129631,my greatest pain in life is that i will never ...,MY GREATEST PAIN IN LIFE IS THAT I WILL NEVER ...,My Greatest Pain In Life Is That I Will Never ...,17,17,True,My greatest pain in life is that I art never b...,[],"[My, greatest, pain, in, life, is, that, I, wi...",My,live,[My greatest pain in life is that I will never...,2,17,1.000000
9,Only free thinkers,2026-01-27 18:50:11.208269,only free thinkers,ONLY FREE THINKERS,Only Free Thinkers,3,3,False,Only free thinkers,[Only],"[Only, free, thinkers]",Only,thinkers,[Only free thinkers],1,3,1.000000

## Question 12: Timestamp Parsing and Time-based Analysis

Use regex to extract different components from timestamps and create a comprehensive time-based analysis of when quotes were collected.

In [47]:
quotes_df

,quote,timestamp,quote_lower,quote_upper,quote_title,word_count,word_count_regex,music_flag,quote_music_replaced,capital_words,words,first_word,last_word,sentences,num_sentences,unique_words,lexical_diversity
0,I spoke to Dave Chapelle for two hours this mo...,2026-01-27 18:49:25.534593,i spoke to dave chapelle for two hours this mo...,I SPOKE TO DAVE CHAPELLE FOR TWO HOURS THIS MO...,I Spoke To Dave Chapelle For Two Hours This Mo...,16,16,False,I spoke to Dave Chapelle for two hours this mo...,"[Dave, Chapelle, Socrates]","[I, spoke, to, Dave, Chapelle, for, two, hours...",I,Socrates,[I spoke to Dave Chapelle for two hours this m...,2,16,1.000000
1,We as a people will heal. We will insure the w...,2026-01-27 18:49:30.606753,we as a people will heal. we will insure the w...,WE AS A PEOPLE WILL HEAL. WE WILL INSURE THE W...,We As A People Will Heal. We Will Insure The W...,15,15,True,We as a people art heal. We art insure the wel...,[],"[We, as, a, people, will, heal., We, will, ins...",We,other,"[We as a people will heal, We will insure the...",2,13,0.866667
2,2024,2026-01-27 18:49:35.679028,2024,2024,2024,1,1,False,2024,[],[2024],2024,2024,[2024],1,1,1.000000
3,There's so many lonely emojis man,2026-01-27 18:49:40.728923,there's so many lonely emojis man,THERE'S SO MANY LONELY EMOJIS MAN,There'S So Many Lonely Emojis Man,6,7,False,There's so many lonely emojis man,[There],"[There's, so, many, lonely, emojis, man]",There,man,[There's so many lonely emojis man],1,6,1.000000
4,George Bush doesn't care about black people,2026-01-27 18:49:45.800520,george bush doesn't care about black people,GEORGE BUSH DOESN'T CARE ABOUT BLACK PEOPLE,George Bush Doesn'T Care About Black People,7,8,False,George Bush doesn't care about black people,"[George, Bush]","[George, Bush, doesn't, care, about, black, pe...",George,people,[George Bush doesn't care about black people],1,7,1.000000
5,I wish I had a friend like me,2026-01-27 18:49:50.868014,i wish i had a friend like me,I WISH I HAD A FRIEND LIKE ME,I Wish I Had A Friend Like Me,8,8,False,I wish I had a friend like me,[],"[I, wish, I, had, a, friend, like, me]",I,me,[I wish I had a friend like me],1,7,0.875000
6,Truth is my goal. Controversy is my gym. I'll ...,2026-01-27 18:49:55.986156,truth is my goal. controversy is my gym. i'll ...,TRUTH IS MY GOAL. CONTROVERSY IS MY GYM. I'LL ...,Truth Is My Goal. Controversy Is My Gym. I'Ll ...,21,22,False,Truth is my goal. Controversy is my gym. I'll ...,"[Truth, Controversy]","[Truth, is, my, goal., Controversy, is, my, gy...",Truth,truth,"[Truth is my goal, Controversy is my gym, I'...",3,17,0.809524
7,We must and will cure homelessness and hunger....,2026-01-27 18:50:01.061949,we must and will cure homelessness and hunger....,WE MUST AND WILL CURE HOMELESSNESS AND HUNGER....,We Must And Will Cure Homelessness And Hunger....,15,15,True,We must and art cure homelessness and hunger. ...,[],"[We, must, and, will, cure, homelessness, and,...",We,species,[We must and will cure homelessness and hunger...,2,13,0.866667
8,My greatest pain in life is that I will never ...,2026-01-27 18:50:06.129631,my greatest pain in life is that i will never ...,MY GREATEST PAIN IN LIFE IS THAT I WILL NEVER ...,My Greatest Pain In Life Is That I Will Never ...,17,17,True,My greatest pain in life is that I art never b...,[],"[My, greatest, pain, in, life, is, that, I, wi...",My,live,[My greatest pain in life is that I will never...,2,17,1.000000
9,Only free thinkers,2026-01-27 18:50:11.208269,only free thinkers,ONLY FREE THINKERS,Only Free Thinkers,3,3,False,Only free thinkers,[Only],"[Only, free, thinkers]",Only,thinkers,[Only free thinkers],1,3,1.000000

In [48]:
# Convert timestamp column to string for regex operations
quotes_df["timestamp_str"] = quotes_df["timestamp"].astype(str)

# Extract different timestamp components using regex
quotes_df["year"] = quotes_df["timestamp_str"].str.extract(r"(\d{4})-")
quotes_df["month"] = quotes_df["timestamp_str"].str.extract(r"-(\d{2})-")
quotes_df["day"] = quotes_df["timestamp_str"].str.extract(r"-(\d{2}) ")
quotes_df["hour"] = quotes_df["timestamp_str"].str.extract(r" (\d{2}):")
quotes_df["minute"] = quotes_df["timestamp_str"].str.extract(r":(\d{2}):")
quotes_df["second"] = quotes_df["timestamp_str"].str.extract(r":(\d{2})\.")

quotes_df

,quote,timestamp,quote_lower,quote_upper,quote_title,word_count,word_count_regex,music_flag,quote_music_replaced,capital_words,...,num_sentences,unique_words,lexical_diversity,timestamp_str,year,month,day,hour,minute,second
0,I spoke to Dave Chapelle for two hours this mo...,2026-01-27 18:49:25.534593,i spoke to dave chapelle for two hours this mo...,I SPOKE TO DAVE CHAPELLE FOR TWO HOURS THIS MO...,I Spoke To Dave Chapelle For Two Hours This Mo...,16,16,False,I spoke to Dave Chapelle for two hours this mo...,"[Dave, Chapelle, Socrates]",...,2,16,1.000000,2026-01-27 18:49:25.534593,2026,01,27,18,49,25
1,We as a people will heal. We will insure the w...,2026-01-27 18:49:30.606753,we as a people will heal. we will insure the w...,WE AS A PEOPLE WILL HEAL. WE WILL INSURE THE W...,We As A People Will Heal. We Will Insure The W...,15,15,True,We as a people art heal. We art insure the wel...,[],...,2,13,0.866667,2026-01-27 18:49:30.606753,2026,01,27,18,49,30
2,2024,2026-01-27 18:49:35.679028,2024,2024,2024,1,1,False,2024,[],...,1,1,1.000000,2026-01-27 18:49:35.679028,2026,01,27,18,49,35
3,There's so many lonely emojis man,2026-01-27 18:49:40.728923,there's so many lonely emojis man,THERE'S SO MANY LONELY EMOJIS MAN,There'S So Many Lonely Emojis Man,6,7,False,There's so many lonely emojis man,[There],...,1,6,1.000000,2026-01-27 18:49:40.728923,2026,01,27,18,49,40
4,George Bush doesn't care about black people,2026-01-27 18:49:45.800520,george bush doesn't care about black people,GEORGE BUSH DOESN'T CARE ABOUT BLACK PEOPLE,George Bush Doesn'T Care About Black People,7,8,False,George Bush doesn't care about black people,"[George, Bush]",...,1,7,1.000000,2026-01-27 18:49:45.800520,2026,01,27,18,49,45
5,I wish I had a friend like me,2026-01-27 18:49:50.868014,i wish i had a friend like me,I WISH I HAD A FRIEND LIKE ME,I Wish I Had A Friend Like Me,8,8,False,I wish I had a friend like me,[],...,1,7,0.875000,2026-01-27 18:49:50.868014,2026,01,27,18,49,50
6,Truth is my goal. Controversy is my gym. I'll ...,2026-01-27 18:49:55.986156,truth is my goal. controversy is my gym. i'll ...,TRUTH IS MY GOAL. CONTROVERSY IS MY GYM. I'LL ...,Truth Is My Goal. Controversy Is My Gym. I'Ll ...,21,22,False,Truth is my goal. Controversy is my gym. I'll ...,"[Truth, Controversy]",...,3,17,0.809524,2026-01-27 18:49:55.986156,2026,01,27,18,49,55
7,We must and will cure homelessness and hunger....,2026-01-27 18:50:01.061949,we must and will cure homelessness and hunger....,WE MUST AND WILL CURE HOMELESSNESS AND HUNGER....,We Must And Will Cure Homelessness And Hunger....,15,15,True,We must and art cure homelessness and hunger. ...,[],...,2,13,0.866667,2026-01-27 18:50:01.061949,2026,01,27,18,50,01
8,My greatest pain in life is that I will never ...,2026-01-27 18:50:06.129631,my greatest pain in life is that i will never ...,MY GREATEST PAIN IN LIFE IS THAT I WILL NEVER ...,My Greatest Pain In Life Is That I Will Never ...,17,17,True,My greatest pain in life is that I art never b...,[],...,2,17,1.000000,2026-01-27 18:50:06.129631,2026,01,27,18,50,06
9,Only free thinkers,2026-01-27 18:50:11.208269,only free thinkers,ONLY FREE THINKERS,Only Free Thinkers,3,3,False,Only free thinkers,[Only],...,1,3,1.000000,2026-01-27 18:50:11.208269,2026,01,27,18,50,11